/*
 * Generated by Bluespec Compiler, version 2022.01 (build 066c7a8)
 * 
 * On Thu Jan 12 14:57:22 CST 2023
 * 
 */

/* Generation options: */
#ifndef __mkDecCounter_h__
#define __mkDecCounter_h__

#include "Types.h"
#include "bluesim_kernel_api.h"
#include <stdio.h>
#include <fstream>
#include <string>
#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkDecCounter module */
class MOD_mkDecCounter : public Module {
 
 public:
	void print_changelists() {
		printf("counter(mkDecCounter)\n");
		printf("\n");
	}
	void generate_testbench(uint64_t sim_time, std::string cur_hierachy) {
		std::ofstream fout(cur_hierachy + ".v");
		std::string out_pre;
		std::string out_post;
		out_pre += "module testbench();\n";
		out_pre += " reg CLK, RST_N;\n";
		out_post += "always begin\n\t#5 CLK = ~CLK;\nend\n";
		out_post += "initial begin\n\tRST_N = 0;\n\t#1 CLK = 1;\n\t#1RST_n = 1;\nend\n";
		out_post += " // for en_regs \n\n";
		out_pre += " mkDecCounter U1(.CLK(CLK), \n\t\t.RST_N(RST_N), \n\t\t.count(), \n\t\t.RDY_count(), \n\t\t.overflow(), \n\t\t.RDY_overflow());\n";
		out_post += "initial begin\n";
		out_post += "\t#" + std::to_string(sim_time) + " $finish;\n";
		out_post += "end\n";
		fout << out_pre << out_post;
	}
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_cnt;
  MOD_Reg<tUInt8> INST_mycnt;
 
 /* Constructor */
 public:
  MOD_mkDecCounter(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt8 DEF_b__h107;
  tUInt8 DEF_cnt_ULT_9___d2;
 
 /* Rules */
 public:
  void RL_run_counter();
  void RL_run_mycnt();
 
 /* Methods */
 public:
  tUInt8 METH_count();
  tUInt8 METH_RDY_count();
  tUInt8 METH_overflow();
  tUInt8 METH_RDY_overflow();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkDecCounter &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkDecCounter &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkDecCounter &backing);
};

#endif /* ifndef __mkDecCounter_h__ */
