/*
 * Generated by Bluespec Compiler, version 2022.01 (build 066c7a8)
 * 
 * On Fri Dec 23 17:42:32 CST 2022
 * 
 */
#include "bluesim_primitives.h"
#include "mkTb.h"


/* Literal declarations */
static unsigned int const UWide_literal_88_h2aaaaaaaaaaaaaaaaaaaaa_arr[] = { 2863311530u,
									     2863311530u,
									     2796202u };
static tUWide const UWide_literal_88_h2aaaaaaaaaaaaaaaaaaaaa(88u,
							     UWide_literal_88_h2aaaaaaaaaaaaaaaaaaaaa_arr);


/* String declarations */
static std::string const __str_literal_4("  Error: file %s header is not P5", 33u);
static std::string const __str_literal_5("  Error: file %s invalid format", 31u);
static std::string const __str_literal_9("  Error: image width or height is not multiple of 8",
					 51u);
static std::string const __str_literal_3("  Error: invalid file: %s", 25u);
static std::string const __str_literal_6("  Image load done, width=%5d, height=%5d", 40u);
static std::string const __str_literal_10("%032x", 5u);
static std::string const __str_literal_11("Error: \"PgmReader.bsv\", line 32, column 7: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_pgm_reader_fsm_action_l32c7]\n  and [RL_pgm_reader_fsm_action_f_init_l42c7, RL_pgm_reader_fsm_action_l42c30,\n  RL_pgm_reader_fsm_action_f_update_l42c7,\n  RL_pgm_reader_fsm_action_f_init_l52c7, RL_pgm_reader_fsm_action_l52c28,\n  RL_pgm_reader_fsm_action_f_update_l52c7,\n  RL_pgm_reader_fsm_action_f_init_l66c7,\n  RL_pgm_reader_fsm_action_f_init_l67c10, RL_pgm_reader_fsm_action_l67c33,\n  RL_pgm_reader_fsm_action_f_update_l67c10, RL_pgm_reader_fsm_action_l71c20,\n  RL_pgm_reader_fsm_action_f_update_l66c7, RL_pgm_reader_fsm_action_l74c7,\n  RL_pgm_reader_fsm_action_l75c7] ) fired in the same clock cycle.\n",
					  703u);
static std::string const __str_literal_12("Error: \"PgmReader.bsv\", line 42, column 12: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_pgm_reader_fsm_action_f_init_l42c7] and\n  [RL_pgm_reader_fsm_action_l42c30, RL_pgm_reader_fsm_action_f_update_l42c7,\n  RL_pgm_reader_fsm_action_f_init_l52c7, RL_pgm_reader_fsm_action_l52c28,\n  RL_pgm_reader_fsm_action_f_update_l52c7,\n  RL_pgm_reader_fsm_action_f_init_l66c7,\n  RL_pgm_reader_fsm_action_f_init_l67c10, RL_pgm_reader_fsm_action_l67c33,\n  RL_pgm_reader_fsm_action_f_update_l67c10, RL_pgm_reader_fsm_action_l71c20,\n  RL_pgm_reader_fsm_action_f_update_l66c7, RL_pgm_reader_fsm_action_l74c7,\n  RL_pgm_reader_fsm_action_l75c7] ) fired in the same clock cycle.\n",
					  672u);
static std::string const __str_literal_14("Error: \"PgmReader.bsv\", line 42, column 23: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_pgm_reader_fsm_action_f_update_l42c7] and\n  [RL_pgm_reader_fsm_action_f_init_l52c7, RL_pgm_reader_fsm_action_l52c28,\n  RL_pgm_reader_fsm_action_f_update_l52c7,\n  RL_pgm_reader_fsm_action_f_init_l66c7,\n  RL_pgm_reader_fsm_action_f_init_l67c10, RL_pgm_reader_fsm_action_l67c33,\n  RL_pgm_reader_fsm_action_f_update_l67c10, RL_pgm_reader_fsm_action_l71c20,\n  RL_pgm_reader_fsm_action_f_update_l66c7, RL_pgm_reader_fsm_action_l74c7,\n  RL_pgm_reader_fsm_action_l75c7] ) fired in the same clock cycle.\n",
					  598u);
static std::string const __str_literal_13("Error: \"PgmReader.bsv\", line 42, column 30: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_pgm_reader_fsm_action_l42c30]\n  and [RL_pgm_reader_fsm_action_f_update_l42c7,\n  RL_pgm_reader_fsm_action_f_init_l52c7, RL_pgm_reader_fsm_action_l52c28,\n  RL_pgm_reader_fsm_action_f_update_l52c7,\n  RL_pgm_reader_fsm_action_f_init_l66c7,\n  RL_pgm_reader_fsm_action_f_init_l67c10, RL_pgm_reader_fsm_action_l67c33,\n  RL_pgm_reader_fsm_action_f_update_l67c10, RL_pgm_reader_fsm_action_l71c20,\n  RL_pgm_reader_fsm_action_f_update_l66c7, RL_pgm_reader_fsm_action_l74c7,\n  RL_pgm_reader_fsm_action_l75c7] ) fired in the same clock cycle.\n",
					  631u);
static std::string const __str_literal_15("Error: \"PgmReader.bsv\", line 52, column 12: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_pgm_reader_fsm_action_f_init_l52c7] and\n  [RL_pgm_reader_fsm_action_l52c28, RL_pgm_reader_fsm_action_f_update_l52c7,\n  RL_pgm_reader_fsm_action_f_init_l66c7,\n  RL_pgm_reader_fsm_action_f_init_l67c10, RL_pgm_reader_fsm_action_l67c33,\n  RL_pgm_reader_fsm_action_f_update_l67c10, RL_pgm_reader_fsm_action_l71c20,\n  RL_pgm_reader_fsm_action_f_update_l66c7, RL_pgm_reader_fsm_action_l74c7,\n  RL_pgm_reader_fsm_action_l75c7] ) fired in the same clock cycle.\n",
					  555u);
static std::string const __str_literal_17("Error: \"PgmReader.bsv\", line 52, column 23: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_pgm_reader_fsm_action_f_update_l52c7] and\n  [RL_pgm_reader_fsm_action_f_init_l66c7,\n  RL_pgm_reader_fsm_action_f_init_l67c10, RL_pgm_reader_fsm_action_l67c33,\n  RL_pgm_reader_fsm_action_f_update_l67c10, RL_pgm_reader_fsm_action_l71c20,\n  RL_pgm_reader_fsm_action_f_update_l66c7, RL_pgm_reader_fsm_action_l74c7,\n  RL_pgm_reader_fsm_action_l75c7] ) fired in the same clock cycle.\n",
					  481u);
static std::string const __str_literal_16("Error: \"PgmReader.bsv\", line 52, column 28: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_pgm_reader_fsm_action_l52c28]\n  and [RL_pgm_reader_fsm_action_f_update_l52c7,\n  RL_pgm_reader_fsm_action_f_init_l66c7,\n  RL_pgm_reader_fsm_action_f_init_l67c10, RL_pgm_reader_fsm_action_l67c33,\n  RL_pgm_reader_fsm_action_f_update_l67c10, RL_pgm_reader_fsm_action_l71c20,\n  RL_pgm_reader_fsm_action_f_update_l66c7, RL_pgm_reader_fsm_action_l74c7,\n  RL_pgm_reader_fsm_action_l75c7] ) fired in the same clock cycle.\n",
					  514u);
static std::string const __str_literal_18("Error: \"PgmReader.bsv\", line 66, column 12: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_pgm_reader_fsm_action_f_init_l66c7] and\n  [RL_pgm_reader_fsm_action_f_init_l67c10, RL_pgm_reader_fsm_action_l67c33,\n  RL_pgm_reader_fsm_action_f_update_l67c10, RL_pgm_reader_fsm_action_l71c20,\n  RL_pgm_reader_fsm_action_f_update_l66c7, RL_pgm_reader_fsm_action_l74c7,\n  RL_pgm_reader_fsm_action_l75c7] ) fired in the same clock cycle.\n",
					  438u);
static std::string const __str_literal_23("Error: \"PgmReader.bsv\", line 66, column 34: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_pgm_reader_fsm_action_f_update_l66c7] and\n  [RL_pgm_reader_fsm_action_l74c7, RL_pgm_reader_fsm_action_l75c7] ) fired in\n  the same clock cycle.\n",
					  247u);
static std::string const __str_literal_19("Error: \"PgmReader.bsv\", line 67, column 15: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_pgm_reader_fsm_action_f_init_l67c10] and\n  [RL_pgm_reader_fsm_action_l67c33, RL_pgm_reader_fsm_action_f_update_l67c10,\n  RL_pgm_reader_fsm_action_l71c20, RL_pgm_reader_fsm_action_f_update_l66c7,\n  RL_pgm_reader_fsm_action_l74c7, RL_pgm_reader_fsm_action_l75c7] ) fired in\n  the same clock cycle.\n",
					  399u);
static std::string const __str_literal_21("Error: \"PgmReader.bsv\", line 67, column 26: (R0001)\n  Mutually exclusive rules (from the ME sets\n  [RL_pgm_reader_fsm_action_f_update_l67c10] and\n  [RL_pgm_reader_fsm_action_l71c20, RL_pgm_reader_fsm_action_f_update_l66c7,\n  RL_pgm_reader_fsm_action_l74c7, RL_pgm_reader_fsm_action_l75c7] ) fired in\n  the same clock cycle.\n",
					  324u);
static std::string const __str_literal_20("Error: \"PgmReader.bsv\", line 67, column 33: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_pgm_reader_fsm_action_l67c33]\n  and [RL_pgm_reader_fsm_action_f_update_l67c10,\n  RL_pgm_reader_fsm_action_l71c20, RL_pgm_reader_fsm_action_f_update_l66c7,\n  RL_pgm_reader_fsm_action_l74c7, RL_pgm_reader_fsm_action_l75c7] ) fired in\n  the same clock cycle.\n",
					  357u);
static std::string const __str_literal_22("Error: \"PgmReader.bsv\", line 71, column 20: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_pgm_reader_fsm_action_l71c20]\n  and [RL_pgm_reader_fsm_action_f_update_l66c7,\n  RL_pgm_reader_fsm_action_l74c7, RL_pgm_reader_fsm_action_l75c7] ) fired in\n  the same clock cycle.\n",
					  280u);
static std::string const __str_literal_24("Error: \"PgmReader.bsv\", line 74, column 7: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_pgm_reader_fsm_action_l74c7]\n  and [RL_pgm_reader_fsm_action_l75c7] ) fired in the same clock cycle.\n",
					  201u);
static std::string const __str_literal_28("Error: \"StmtFSM.bs\", line 41, column 0: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_d_init_np] and\n  [RL_action_np] ) fired in the same clock cycle.\n",
					  169u);
static std::string const __str_literal_25("Error: \"TbJpegEncoder.bsv\", line 20, column 7: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l20c7] and\n  [RL_action_l25c7, RL_action_l36c10, RL_action_d_init_np, RL_action_np] )\n  fired in the same clock cycle.\n",
					  230u);
static std::string const __str_literal_26("Error: \"TbJpegEncoder.bsv\", line 25, column 7: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l25c7] and\n  [RL_action_l36c10, RL_action_d_init_np, RL_action_np] ) fired in the same\n  clock cycle.\n",
					  213u);
static std::string const __str_literal_27("Error: \"TbJpegEncoder.bsv\", line 36, column 10: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l36c10] and\n  [RL_action_d_init_np, RL_action_np] ) fired in the same clock cycle.\n",
					  195u);
static std::string const __str_literal_1("img/in011.pgm", 13u);
static std::string const __str_literal_7("out.jpg.txt", 11u);
static std::string const __str_literal_2("rb", 2u);
static std::string const __str_literal_8("w", 1u);


/* Constructor */
MOD_mkTb::MOD_mkTb(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_abort(simHdl, "abort", this, 1u, (tUInt8)0u),
    INST_jj_delay_count(simHdl, "jj_delay_count", this, 14u, 0u, (tUInt8)0u),
    INST_jpg_encoder(simHdl, "jpg_encoder", this),
    INST_jpg_file(simHdl, "jpg_file", this, 32u, 0u, (tUInt8)0u),
    INST_pgm_reader_filep(simHdl, "pgm_reader_filep", this, 32u, 0u, (tUInt8)0u),
    INST_pgm_reader_fsm_abort(simHdl, "pgm_reader_fsm_abort", this, 1u, (tUInt8)0u),
    INST_pgm_reader_fsm_start_reg(simHdl, "pgm_reader_fsm_start_reg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_pgm_reader_fsm_start_reg_1(simHdl,
				    "pgm_reader_fsm_start_reg_1",
				    this,
				    1u,
				    (tUInt8)0u,
				    (tUInt8)0u),
    INST_pgm_reader_fsm_start_reg_2(simHdl, "pgm_reader_fsm_start_reg_2", this, 1u, (tUInt8)0u),
    INST_pgm_reader_fsm_start_wire(simHdl, "pgm_reader_fsm_start_wire", this, 1u, (tUInt8)0u),
    INST_pgm_reader_fsm_state_can_overlap(simHdl,
					  "pgm_reader_fsm_state_can_overlap",
					  this,
					  1u,
					  (tUInt8)1u,
					  (tUInt8)0u),
    INST_pgm_reader_fsm_state_fired(simHdl,
				    "pgm_reader_fsm_state_fired",
				    this,
				    1u,
				    (tUInt8)0u,
				    (tUInt8)0u),
    INST_pgm_reader_fsm_state_fired_1(simHdl, "pgm_reader_fsm_state_fired_1", this, 1u, (tUInt8)0u),
    INST_pgm_reader_fsm_state_mkFSMstate(simHdl,
					 "pgm_reader_fsm_state_mkFSMstate",
					 this,
					 5u,
					 (tUInt8)0u,
					 (tUInt8)0u),
    INST_pgm_reader_fsm_state_overlap_pw(simHdl, "pgm_reader_fsm_state_overlap_pw", this, 0u),
    INST_pgm_reader_fsm_state_set_pw(simHdl, "pgm_reader_fsm_state_set_pw", this, 0u),
    INST_pgm_reader_i(simHdl, "pgm_reader_i", this, 32u, 0u, (tUInt8)0u),
    INST_pgm_reader_image_params_0(simHdl, "pgm_reader_image_params_0", this, 32u, 0u, (tUInt8)0u),
    INST_pgm_reader_image_params_1(simHdl, "pgm_reader_image_params_1", this, 32u, 0u, (tUInt8)0u),
    INST_pgm_reader_image_params_2(simHdl, "pgm_reader_image_params_2", this, 32u, 0u, (tUInt8)0u),
    INST_pgm_reader_j(simHdl, "pgm_reader_j", this, 32u, 0u, (tUInt8)0u),
    INST_pgm_reader_load_pixels(simHdl, "pgm_reader_load_pixels", this, 64u, 0llu, (tUInt8)0u),
    INST_pgm_reader_pixel_fifo_memory(simHdl,
				      "pgm_reader_pixel_fifo_memory",
				      this,
				      (tUInt8)0u,
				      22u,
				      64u,
				      4194304u,
				      2u),
    INST_pgm_reader_pixel_fifo_pwClear(simHdl, "pgm_reader_pixel_fifo_pwClear", this, 0u),
    INST_pgm_reader_pixel_fifo_pwDequeue(simHdl, "pgm_reader_pixel_fifo_pwDequeue", this, 0u),
    INST_pgm_reader_pixel_fifo_pwEnqueue(simHdl, "pgm_reader_pixel_fifo_pwEnqueue", this, 0u),
    INST_pgm_reader_pixel_fifo_rCache(simHdl,
				      "pgm_reader_pixel_fifo_rCache",
				      this,
				      88u,
				      bs_wide_tmp(88u).set_bits_in_word(UWide_literal_88_h2aaaaaaaaaaaaaaaaaaaaa.get_bits_in_word32(2u,
																    0u,
																    24u),
									2u,
									0u,
									24u).set_whole_word(UWide_literal_88_h2aaaaaaaaaaaaaaaaaaaaa.get_whole_word(1u),
											    1u).set_whole_word(UWide_literal_88_h2aaaaaaaaaaaaaaaaaaaaa.get_whole_word(0u),
													       0u),
				      (tUInt8)0u),
    INST_pgm_reader_pixel_fifo_rRdPtr(simHdl,
				      "pgm_reader_pixel_fifo_rRdPtr",
				      this,
				      23u,
				      0u,
				      (tUInt8)0u),
    INST_pgm_reader_pixel_fifo_rWrPtr(simHdl,
				      "pgm_reader_pixel_fifo_rWrPtr",
				      this,
				      23u,
				      0u,
				      (tUInt8)0u),
    INST_pgm_reader_pixel_fifo_wDataIn(simHdl, "pgm_reader_pixel_fifo_wDataIn", this, 64u, (tUInt8)0u),
    INST_pgm_reader_pixel_fifo_wDataOut(simHdl,
					"pgm_reader_pixel_fifo_wDataOut",
					this,
					64u,
					(tUInt8)0u),
    INST_running(simHdl, "running", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_start_reg(simHdl, "start_reg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_start_reg_1(simHdl, "start_reg_1", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_start_reg_2(simHdl, "start_reg_2", this, 1u, (tUInt8)0u),
    INST_start_wire(simHdl, "start_wire", this, 1u, (tUInt8)0u),
    INST_state_can_overlap(simHdl, "state_can_overlap", this, 1u, (tUInt8)1u, (tUInt8)0u),
    INST_state_fired(simHdl, "state_fired", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_state_fired_1(simHdl, "state_fired_1", this, 1u, (tUInt8)0u),
    INST_state_mkFSMstate(simHdl, "state_mkFSMstate", this, 3u, (tUInt8)0u, (tUInt8)0u),
    INST_state_overlap_pw(simHdl, "state_overlap_pw", this, 0u),
    INST_state_set_pw(simHdl, "state_set_pw", this, 0u),
    PORT_RST_N((tUInt8)1u),
    DEF_TASK_fgetc___d156(2863311530u),
    DEF_b__h51881(2863311530u),
    DEF_b__h50673(2863311530u),
    DEF_TASK_fopen___d237(2863311530u),
    DEF_TASK_fopen___d67(2863311530u),
    DEF_x_get__h58249(128u),
    DEF_pgm_reader_pixel_fifo_rCache___d23(88u),
    DEF__1_CONCAT_pgm_reader_pixel_fifo_rWrPtr_read_CON_ETC___d14(88u)
{
  symbol_count = 128u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTb::init_symbols_0()
{
  init_symbol(&symbols[0u], "__me_check_10", SYM_RULE);
  init_symbol(&symbols[1u], "__me_check_11", SYM_RULE);
  init_symbol(&symbols[2u], "__me_check_12", SYM_RULE);
  init_symbol(&symbols[3u], "__me_check_13", SYM_RULE);
  init_symbol(&symbols[4u], "__me_check_14", SYM_RULE);
  init_symbol(&symbols[5u], "__me_check_15", SYM_RULE);
  init_symbol(&symbols[6u], "__me_check_16", SYM_RULE);
  init_symbol(&symbols[7u], "__me_check_17", SYM_RULE);
  init_symbol(&symbols[8u], "__me_check_18", SYM_RULE);
  init_symbol(&symbols[9u], "__me_check_19", SYM_RULE);
  init_symbol(&symbols[10u], "__me_check_20", SYM_RULE);
  init_symbol(&symbols[11u], "__me_check_21", SYM_RULE);
  init_symbol(&symbols[12u], "__me_check_31", SYM_RULE);
  init_symbol(&symbols[13u], "__me_check_32", SYM_RULE);
  init_symbol(&symbols[14u], "__me_check_33", SYM_RULE);
  init_symbol(&symbols[15u], "__me_check_34", SYM_RULE);
  init_symbol(&symbols[16u], "__me_check_8", SYM_RULE);
  init_symbol(&symbols[17u], "__me_check_9", SYM_RULE);
  init_symbol(&symbols[18u], "abort", SYM_MODULE, &INST_abort);
  init_symbol(&symbols[19u], "b__h24176", SYM_DEF, &DEF_b__h24176, 32u);
  init_symbol(&symbols[20u], "jj_delay_count", SYM_MODULE, &INST_jj_delay_count);
  init_symbol(&symbols[21u], "jpg_encoder", SYM_MODULE, &INST_jpg_encoder);
  init_symbol(&symbols[22u], "jpg_file", SYM_MODULE, &INST_jpg_file);
  init_symbol(&symbols[23u], "pgm_reader_filep", SYM_MODULE, &INST_pgm_reader_filep);
  init_symbol(&symbols[24u], "pgm_reader_fsm_abort", SYM_MODULE, &INST_pgm_reader_fsm_abort);
  init_symbol(&symbols[25u], "pgm_reader_fsm_start_reg", SYM_MODULE, &INST_pgm_reader_fsm_start_reg);
  init_symbol(&symbols[26u],
	      "pgm_reader_fsm_start_reg_1",
	      SYM_MODULE,
	      &INST_pgm_reader_fsm_start_reg_1);
  init_symbol(&symbols[27u],
	      "pgm_reader_fsm_start_reg_2",
	      SYM_MODULE,
	      &INST_pgm_reader_fsm_start_reg_2);
  init_symbol(&symbols[28u],
	      "pgm_reader_fsm_start_wire",
	      SYM_MODULE,
	      &INST_pgm_reader_fsm_start_wire);
  init_symbol(&symbols[29u],
	      "pgm_reader_fsm_state_can_overlap",
	      SYM_MODULE,
	      &INST_pgm_reader_fsm_state_can_overlap);
  init_symbol(&symbols[30u],
	      "pgm_reader_fsm_state_fired",
	      SYM_MODULE,
	      &INST_pgm_reader_fsm_state_fired);
  init_symbol(&symbols[31u],
	      "pgm_reader_fsm_state_fired_1",
	      SYM_MODULE,
	      &INST_pgm_reader_fsm_state_fired_1);
  init_symbol(&symbols[32u],
	      "pgm_reader_fsm_state_mkFSMstate",
	      SYM_MODULE,
	      &INST_pgm_reader_fsm_state_mkFSMstate);
  init_symbol(&symbols[33u],
	      "pgm_reader_fsm_state_overlap_pw",
	      SYM_MODULE,
	      &INST_pgm_reader_fsm_state_overlap_pw);
  init_symbol(&symbols[34u],
	      "pgm_reader_fsm_state_set_pw",
	      SYM_MODULE,
	      &INST_pgm_reader_fsm_state_set_pw);
  init_symbol(&symbols[35u], "pgm_reader_i", SYM_MODULE, &INST_pgm_reader_i);
  init_symbol(&symbols[36u],
	      "pgm_reader_image_params_0",
	      SYM_MODULE,
	      &INST_pgm_reader_image_params_0);
  init_symbol(&symbols[37u],
	      "pgm_reader_image_params_1",
	      SYM_MODULE,
	      &INST_pgm_reader_image_params_1);
  init_symbol(&symbols[38u],
	      "pgm_reader_image_params_2",
	      SYM_MODULE,
	      &INST_pgm_reader_image_params_2);
  init_symbol(&symbols[39u], "pgm_reader_j", SYM_MODULE, &INST_pgm_reader_j);
  init_symbol(&symbols[40u], "pgm_reader_load_pixels", SYM_MODULE, &INST_pgm_reader_load_pixels);
  init_symbol(&symbols[41u],
	      "pgm_reader_pixel_fifo_memory",
	      SYM_MODULE,
	      &INST_pgm_reader_pixel_fifo_memory);
  init_symbol(&symbols[42u],
	      "pgm_reader_pixel_fifo_pwClear",
	      SYM_MODULE,
	      &INST_pgm_reader_pixel_fifo_pwClear);
  init_symbol(&symbols[43u],
	      "pgm_reader_pixel_fifo_pwDequeue",
	      SYM_MODULE,
	      &INST_pgm_reader_pixel_fifo_pwDequeue);
  init_symbol(&symbols[44u],
	      "pgm_reader_pixel_fifo_pwEnqueue",
	      SYM_MODULE,
	      &INST_pgm_reader_pixel_fifo_pwEnqueue);
  init_symbol(&symbols[45u],
	      "pgm_reader_pixel_fifo_rCache",
	      SYM_MODULE,
	      &INST_pgm_reader_pixel_fifo_rCache);
  init_symbol(&symbols[46u],
	      "pgm_reader_pixel_fifo_rRdPtr",
	      SYM_MODULE,
	      &INST_pgm_reader_pixel_fifo_rRdPtr);
  init_symbol(&symbols[47u],
	      "pgm_reader_pixel_fifo_rWrPtr",
	      SYM_MODULE,
	      &INST_pgm_reader_pixel_fifo_rWrPtr);
  init_symbol(&symbols[48u],
	      "pgm_reader_pixel_fifo_wDataIn",
	      SYM_MODULE,
	      &INST_pgm_reader_pixel_fifo_wDataIn);
  init_symbol(&symbols[49u],
	      "pgm_reader_pixel_fifo_wDataOut",
	      SYM_MODULE,
	      &INST_pgm_reader_pixel_fifo_wDataOut);
  init_symbol(&symbols[50u], "RL_action_d_init_np", SYM_RULE);
  init_symbol(&symbols[51u], "RL_action_l20c7", SYM_RULE);
  init_symbol(&symbols[52u], "RL_action_l25c7", SYM_RULE);
  init_symbol(&symbols[53u], "RL_action_l36c10", SYM_RULE);
  init_symbol(&symbols[54u], "RL_action_np", SYM_RULE);
  init_symbol(&symbols[55u], "RL_auto_finish", SYM_RULE);
  init_symbol(&symbols[56u], "RL_auto_start", SYM_RULE);
  init_symbol(&symbols[57u], "RL_fsm_start", SYM_RULE);
  init_symbol(&symbols[58u], "RL_idle_l19c15", SYM_RULE);
  init_symbol(&symbols[59u], "RL_idle_l19c15_1", SYM_RULE);
  init_symbol(&symbols[60u], "RL_pgm_reader_fsm_action_f_init_l42c7", SYM_RULE);
  init_symbol(&symbols[61u], "RL_pgm_reader_fsm_action_f_init_l52c7", SYM_RULE);
  init_symbol(&symbols[62u], "RL_pgm_reader_fsm_action_f_init_l66c7", SYM_RULE);
  init_symbol(&symbols[63u], "RL_pgm_reader_fsm_action_f_init_l67c10", SYM_RULE);
  init_symbol(&symbols[64u], "RL_pgm_reader_fsm_action_f_update_l42c7", SYM_RULE);
  init_symbol(&symbols[65u], "RL_pgm_reader_fsm_action_f_update_l52c7", SYM_RULE);
  init_symbol(&symbols[66u], "RL_pgm_reader_fsm_action_f_update_l66c7", SYM_RULE);
  init_symbol(&symbols[67u], "RL_pgm_reader_fsm_action_f_update_l67c10", SYM_RULE);
  init_symbol(&symbols[68u], "RL_pgm_reader_fsm_action_l32c7", SYM_RULE);
  init_symbol(&symbols[69u], "RL_pgm_reader_fsm_action_l42c30", SYM_RULE);
  init_symbol(&symbols[70u], "RL_pgm_reader_fsm_action_l52c28", SYM_RULE);
  init_symbol(&symbols[71u], "RL_pgm_reader_fsm_action_l67c33", SYM_RULE);
  init_symbol(&symbols[72u], "RL_pgm_reader_fsm_action_l71c20", SYM_RULE);
  init_symbol(&symbols[73u], "RL_pgm_reader_fsm_action_l74c7", SYM_RULE);
  init_symbol(&symbols[74u], "RL_pgm_reader_fsm_action_l75c7", SYM_RULE);
  init_symbol(&symbols[75u], "RL_pgm_reader_fsm_fsm_start", SYM_RULE);
  init_symbol(&symbols[76u], "RL_pgm_reader_fsm_idle_l30c23", SYM_RULE);
  init_symbol(&symbols[77u], "RL_pgm_reader_fsm_restart", SYM_RULE);
  init_symbol(&symbols[78u], "RL_pgm_reader_fsm_start_reg__dreg_update", SYM_RULE);
  init_symbol(&symbols[79u], "RL_pgm_reader_fsm_state_every", SYM_RULE);
  init_symbol(&symbols[80u], "RL_pgm_reader_fsm_state_fired__dreg_update", SYM_RULE);
  init_symbol(&symbols[81u], "RL_pgm_reader_fsm_state_handle_abort", SYM_RULE);
  init_symbol(&symbols[82u], "RL_pgm_reader_pixel_fifo_portA", SYM_RULE);
  init_symbol(&symbols[83u], "RL_pgm_reader_pixel_fifo_portB", SYM_RULE);
  init_symbol(&symbols[84u], "RL_pgm_reader_pixel_fifo_portB_read_data", SYM_RULE);
  init_symbol(&symbols[85u], "RL_pgm_reader_start_fsm", SYM_RULE);
  init_symbol(&symbols[86u], "RL_restart", SYM_RULE);
  init_symbol(&symbols[87u], "RL_start_reg__dreg_update", SYM_RULE);
  init_symbol(&symbols[88u], "RL_state_every", SYM_RULE);
  init_symbol(&symbols[89u], "RL_state_fired__dreg_update", SYM_RULE);
  init_symbol(&symbols[90u], "RL_state_handle_abort", SYM_RULE);
  init_symbol(&symbols[91u], "RL_write_jpg_to_file", SYM_RULE);
  init_symbol(&symbols[92u], "running", SYM_MODULE, &INST_running);
  init_symbol(&symbols[93u], "start_reg", SYM_MODULE, &INST_start_reg);
  init_symbol(&symbols[94u], "start_reg_1", SYM_MODULE, &INST_start_reg_1);
  init_symbol(&symbols[95u], "start_reg_2", SYM_MODULE, &INST_start_reg_2);
  init_symbol(&symbols[96u], "start_wire", SYM_MODULE, &INST_start_wire);
  init_symbol(&symbols[97u], "state_can_overlap", SYM_MODULE, &INST_state_can_overlap);
  init_symbol(&symbols[98u], "state_fired", SYM_MODULE, &INST_state_fired);
  init_symbol(&symbols[99u], "state_fired_1", SYM_MODULE, &INST_state_fired_1);
  init_symbol(&symbols[100u], "state_mkFSMstate", SYM_MODULE, &INST_state_mkFSMstate);
  init_symbol(&symbols[101u], "state_overlap_pw", SYM_MODULE, &INST_state_overlap_pw);
  init_symbol(&symbols[102u], "state_set_pw", SYM_MODULE, &INST_state_set_pw);
  init_symbol(&symbols[103u],
	      "WILL_FIRE_RL_action_d_init_np",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_action_d_init_np,
	      1u);
  init_symbol(&symbols[104u],
	      "WILL_FIRE_RL_action_l20c7",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_action_l20c7,
	      1u);
  init_symbol(&symbols[105u],
	      "WILL_FIRE_RL_action_l25c7",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_action_l25c7,
	      1u);
  init_symbol(&symbols[106u],
	      "WILL_FIRE_RL_action_l36c10",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_action_l36c10,
	      1u);
  init_symbol(&symbols[107u], "WILL_FIRE_RL_action_np", SYM_DEF, &DEF_WILL_FIRE_RL_action_np, 1u);
  init_symbol(&symbols[108u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l42c7",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l42c7,
	      1u);
  init_symbol(&symbols[109u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7,
	      1u);
  init_symbol(&symbols[110u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7,
	      1u);
  init_symbol(&symbols[111u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10,
	      1u);
  init_symbol(&symbols[112u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7,
	      1u);
  init_symbol(&symbols[113u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7,
	      1u);
  init_symbol(&symbols[114u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7,
	      1u);
  init_symbol(&symbols[115u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10,
	      1u);
  init_symbol(&symbols[116u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_l32c7",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l32c7,
	      1u);
  init_symbol(&symbols[117u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_l42c30",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l42c30,
	      1u);
  init_symbol(&symbols[118u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_l52c28",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28,
	      1u);
  init_symbol(&symbols[119u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_l67c33",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33,
	      1u);
  init_symbol(&symbols[120u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_l71c20",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20,
	      1u);
  init_symbol(&symbols[121u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_l74c7",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7,
	      1u);
  init_symbol(&symbols[122u],
	      "WILL_FIRE_RL_pgm_reader_fsm_action_l75c7",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7,
	      1u);
  init_symbol(&symbols[123u], "x__h3193", SYM_DEF, &DEF_x__h3193, 23u);
  init_symbol(&symbols[124u], "x__h52242", SYM_DEF, &DEF_x__h52242, 32u);
  init_symbol(&symbols[125u], "x__h5481", SYM_DEF, &DEF_x__h5481, 23u);
  init_symbol(&symbols[126u], "x__h78533", SYM_DEF, &DEF_x__h78533, 32u);
  init_symbol(&symbols[127u], "x__h78627", SYM_DEF, &DEF_x__h78627, 32u);
}


/* Rule actions */

void MOD_mkTb::RL_pgm_reader_pixel_fifo_portA()
{
  tUInt8 DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas_AND_pgm_ETC___d13;
  tUInt32 DEF_x__h3171;
  tUInt32 DEF_IF_pgm_reader_pixel_fifo_pwClear_whas_THEN_0_E_ETC___d6;
  tUInt64 DEF_IF_pgm_reader_pixel_fifo_pwEnqueue_whas_THEN_I_ETC___d12;
  tUInt64 DEF_IF_pgm_reader_pixel_fifo_wDataIn_whas_THEN_pgm_ETC___d11;
  tUInt32 DEF_x2__h1076;
  tUInt8 DEF_pgm_reader_pixel_fifo_pwEnqueue_whas____d2;
  tUInt8 DEF_pgm_reader_pixel_fifo_pwClear_whas_OR_pgm_read_ETC___d3;
  DEF_pgm_reader_pixel_fifo_pwEnqueue_whas____d2 = INST_pgm_reader_pixel_fifo_pwEnqueue.METH_whas();
  DEF_x__h3193 = INST_pgm_reader_pixel_fifo_rWrPtr.METH_read();
  DEF_pgm_reader_pixel_fifo_pwClear_whas____d1 = INST_pgm_reader_pixel_fifo_pwClear.METH_whas();
  DEF_pgm_reader_pixel_fifo_pwClear_whas_OR_pgm_read_ETC___d3 = DEF_pgm_reader_pixel_fifo_pwClear_whas____d1 || DEF_pgm_reader_pixel_fifo_pwEnqueue_whas____d2;
  DEF_x2__h1076 = (tUInt32)(4194303u & DEF_x__h3193);
  DEF_IF_pgm_reader_pixel_fifo_wDataIn_whas_THEN_pgm_ETC___d11 = INST_pgm_reader_pixel_fifo_wDataIn.METH_whas() ? INST_pgm_reader_pixel_fifo_wDataIn.METH_wget() : 0llu;
  DEF_IF_pgm_reader_pixel_fifo_pwEnqueue_whas_THEN_I_ETC___d12 = DEF_IF_pgm_reader_pixel_fifo_wDataIn_whas_THEN_pgm_ETC___d11;
  DEF_x__h3171 = 8388607u & (DEF_x__h3193 + 1u);
  DEF_IF_pgm_reader_pixel_fifo_pwClear_whas_THEN_0_E_ETC___d6 = DEF_pgm_reader_pixel_fifo_pwClear_whas____d1 ? 0u : DEF_x__h3171;
  DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas___d7 = !DEF_pgm_reader_pixel_fifo_pwClear_whas____d1;
  DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas_AND_pgm_ETC___d13 = DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas___d7 && DEF_pgm_reader_pixel_fifo_pwEnqueue_whas____d2;
  DEF__1_CONCAT_pgm_reader_pixel_fifo_rWrPtr_read_CON_ETC___d14.build_concat(72057594037927935llu & (((((tUInt64)((tUInt8)1u)) << 55u) | (((tUInt64)(DEF_x__h3193)) << 32u)) | (tUInt64)((tUInt32)(DEF_IF_pgm_reader_pixel_fifo_wDataIn_whas_THEN_pgm_ETC___d11 >> 32u))),
									     32u,
									     56u).set_whole_word((tUInt32)(DEF_IF_pgm_reader_pixel_fifo_wDataIn_whas_THEN_pgm_ETC___d11),
												 0u);
  if (DEF_pgm_reader_pixel_fifo_pwClear_whas_OR_pgm_read_ETC___d3)
    INST_pgm_reader_pixel_fifo_rWrPtr.METH_write(DEF_IF_pgm_reader_pixel_fifo_pwClear_whas_THEN_0_E_ETC___d6);
  if (DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas___d7)
    INST_pgm_reader_pixel_fifo_memory.METH_a_put(DEF_pgm_reader_pixel_fifo_pwEnqueue_whas____d2,
						 DEF_x2__h1076,
						 DEF_IF_pgm_reader_pixel_fifo_pwEnqueue_whas_THEN_I_ETC___d12);
  if (DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas_AND_pgm_ETC___d13)
    INST_pgm_reader_pixel_fifo_rCache.METH_write(DEF__1_CONCAT_pgm_reader_pixel_fifo_rWrPtr_read_CON_ETC___d14);
}

void MOD_mkTb::RL_pgm_reader_pixel_fifo_portB()
{
  tUInt32 DEF_IF_pgm_reader_pixel_fifo_pwDequeue_whas__5_THE_ETC___d22;
  tUInt32 DEF_IF_pgm_reader_pixel_fifo_pwClear_whas_THEN_0_E_ETC___d19;
  tUInt32 DEF_x2__h4327;
  tUInt32 DEF_x__h5474;
  tUInt32 DEF_x2__h4345;
  tUInt8 DEF_pgm_reader_pixel_fifo_pwDequeue_whas____d15;
  tUInt8 DEF_pgm_reader_pixel_fifo_pwClear_whas_OR_pgm_read_ETC___d16;
  DEF_pgm_reader_pixel_fifo_pwDequeue_whas____d15 = INST_pgm_reader_pixel_fifo_pwDequeue.METH_whas();
  DEF_x__h5481 = INST_pgm_reader_pixel_fifo_rRdPtr.METH_read();
  DEF_pgm_reader_pixel_fifo_pwClear_whas____d1 = INST_pgm_reader_pixel_fifo_pwClear.METH_whas();
  DEF_pgm_reader_pixel_fifo_pwClear_whas_OR_pgm_read_ETC___d16 = DEF_pgm_reader_pixel_fifo_pwClear_whas____d1 || DEF_pgm_reader_pixel_fifo_pwDequeue_whas____d15;
  DEF_x__h5474 = 8388607u & (DEF_x__h5481 + 1u);
  DEF_x2__h4345 = (tUInt32)(4194303u & DEF_x__h5474);
  DEF_x2__h4327 = (tUInt32)(4194303u & DEF_x__h5481);
  DEF_IF_pgm_reader_pixel_fifo_pwClear_whas_THEN_0_E_ETC___d19 = DEF_pgm_reader_pixel_fifo_pwClear_whas____d1 ? 0u : DEF_x__h5474;
  DEF_IF_pgm_reader_pixel_fifo_pwDequeue_whas__5_THE_ETC___d22 = DEF_pgm_reader_pixel_fifo_pwDequeue_whas____d15 ? DEF_x2__h4345 : DEF_x2__h4327;
  DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas___d7 = !DEF_pgm_reader_pixel_fifo_pwClear_whas____d1;
  if (DEF_pgm_reader_pixel_fifo_pwClear_whas_OR_pgm_read_ETC___d16)
    INST_pgm_reader_pixel_fifo_rRdPtr.METH_write(DEF_IF_pgm_reader_pixel_fifo_pwClear_whas_THEN_0_E_ETC___d19);
  if (DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas___d7)
    INST_pgm_reader_pixel_fifo_memory.METH_b_put((tUInt8)0u,
						 DEF_IF_pgm_reader_pixel_fifo_pwDequeue_whas__5_THE_ETC___d22,
						 12297829382473034410llu);
}

void MOD_mkTb::RL_pgm_reader_pixel_fifo_portB_read_data()
{
  tUInt64 DEF_IF_pgm_reader_pixel_fifo_rCache_3_BIT_87_4_AND_ETC___d30;
  tUInt32 DEF_x__h6638;
  DEF_pgm_reader_pixel_fifo_rCache___d23 = INST_pgm_reader_pixel_fifo_rCache.METH_read();
  DEF_x__h5481 = INST_pgm_reader_pixel_fifo_rRdPtr.METH_read();
  DEF_x__h6638 = DEF_pgm_reader_pixel_fifo_rCache___d23.get_bits_in_word32(2u, 0u, 23u);
  DEF_IF_pgm_reader_pixel_fifo_rCache_3_BIT_87_4_AND_ETC___d30 = DEF_pgm_reader_pixel_fifo_rCache___d23.get_bits_in_word8(2u,
															  23u,
															  1u) && DEF_x__h6638 == DEF_x__h5481 ? primExtract64(64u,
																					      88u,
																					      DEF_pgm_reader_pixel_fifo_rCache___d23,
																					      32u,
																					      63u,
																					      32u,
																					      0u) : INST_pgm_reader_pixel_fifo_memory.METH_b_read();
  INST_pgm_reader_pixel_fifo_wDataOut.METH_wset(DEF_IF_pgm_reader_pixel_fifo_rCache_3_BIT_87_4_AND_ETC___d30);
}

void MOD_mkTb::RL_pgm_reader_fsm_start_reg__dreg_update()
{
  tUInt8 DEF_pgm_reader_fsm_start_reg_2_whas__1_AND_pgm_rea_ETC___d33;
  DEF_pgm_reader_fsm_start_reg_2_whas__1_AND_pgm_rea_ETC___d33 = INST_pgm_reader_fsm_start_reg_2.METH_whas() && INST_pgm_reader_fsm_start_reg_2.METH_wget();
  INST_pgm_reader_fsm_start_reg_1.METH_write(DEF_pgm_reader_fsm_start_reg_2_whas__1_AND_pgm_rea_ETC___d33);
}

void MOD_mkTb::RL_pgm_reader_fsm_state_handle_abort()
{
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)0u);
}

void MOD_mkTb::RL_pgm_reader_fsm_state_fired__dreg_update()
{
  tUInt8 DEF_pgm_reader_fsm_state_fired_1_whas__3_AND_pgm_r_ETC___d45;
  DEF_pgm_reader_fsm_state_fired_1_whas__3_AND_pgm_r_ETC___d45 = INST_pgm_reader_fsm_state_fired_1.METH_whas() && INST_pgm_reader_fsm_state_fired_1.METH_wget();
  INST_pgm_reader_fsm_state_fired.METH_write(DEF_pgm_reader_fsm_state_fired_1_whas__3_AND_pgm_r_ETC___d45);
}

void MOD_mkTb::RL_pgm_reader_fsm_state_every()
{
  tUInt8 DEF_pgm_reader_fsm_state_set_pw_whas__6_OR_NOT_pgm_ETC___d51;
  tUInt8 DEF_pgm_reader_fsm_state_can_overlap__h13893;
  DEF_pgm_reader_fsm_state_can_overlap__h13893 = INST_pgm_reader_fsm_state_can_overlap.METH_read();
  DEF_pgm_reader_fsm_state_set_pw_whas__6_OR_NOT_pgm_ETC___d51 = INST_pgm_reader_fsm_state_set_pw.METH_whas() || (!INST_pgm_reader_fsm_state_overlap_pw.METH_whas() && DEF_pgm_reader_fsm_state_can_overlap__h13893);
  INST_pgm_reader_fsm_state_can_overlap.METH_write(DEF_pgm_reader_fsm_state_set_pw_whas__6_OR_NOT_pgm_ETC___d51);
}

void MOD_mkTb::RL_pgm_reader_fsm_restart()
{
  INST_pgm_reader_fsm_start_wire.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_start_reg_2.METH_wset((tUInt8)1u);
}

void MOD_mkTb::RL_pgm_reader_fsm_action_l32c7()
{
  tUInt8 DEF_NOT_TASK_fopen_7_EQ_0_8___d69;
  tUInt8 DEF_TASK_fopen_7_EQ_0___d68;
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)1u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_TASK_fopen___d67 = dollar_fopen("s,s", &__str_literal_1, &__str_literal_2);
  DEF_TASK_fopen_7_EQ_0___d68 = DEF_TASK_fopen___d67 == 0u;
  DEF_NOT_TASK_fopen_7_EQ_0_8___d69 = !DEF_TASK_fopen_7_EQ_0___d68;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_TASK_fopen_7_EQ_0___d68)
      dollar_error(sim_hdl, this, "s,s", &__str_literal_3, &__str_literal_1);
    if (DEF_TASK_fopen_7_EQ_0___d68)
      dollar_finish(sim_hdl, "32", 1u);
  }
  if (DEF_NOT_TASK_fopen_7_EQ_0_8___d69)
    INST_pgm_reader_filep.METH_write(DEF_TASK_fopen___d67);
}

void MOD_mkTb::RL_pgm_reader_fsm_action_f_init_l42c7()
{
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)2u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  INST_pgm_reader_i.METH_write(0u);
}

void MOD_mkTb::RL_pgm_reader_fsm_action_l42c30()
{
  tUInt8 DEF_NOT_TASK_fgetc_0_EQ_SEL_ARR_0x50_0x35_1_pgm_re_ETC___d84;
  tUInt32 DEF_SEL_ARR_0x50_0x35_1_pgm_reader_i_2___d82;
  DEF_x__h52242 = INST_pgm_reader_i.METH_read();
  DEF_pgm_reader_filep__h50699 = INST_pgm_reader_filep.METH_read();
  switch (DEF_x__h52242) {
  case 0u:
    DEF_SEL_ARR_0x50_0x35_1_pgm_reader_i_2___d82 = 80u;
    break;
  case 1u:
    DEF_SEL_ARR_0x50_0x35_1_pgm_reader_i_2___d82 = 53u;
    break;
  default:
    DEF_SEL_ARR_0x50_0x35_1_pgm_reader_i_2___d82 = 2863311530u;
  }
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)3u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_b__h50673 = dollar_fgetc("32", DEF_pgm_reader_filep__h50699);
  DEF_NOT_TASK_fgetc_0_EQ_SEL_ARR_0x50_0x35_1_pgm_re_ETC___d84 = !(DEF_b__h50673 == DEF_SEL_ARR_0x50_0x35_1_pgm_reader_i_2___d82);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_NOT_TASK_fgetc_0_EQ_SEL_ARR_0x50_0x35_1_pgm_re_ETC___d84)
      dollar_error(sim_hdl, this, "s,s", &__str_literal_4, &__str_literal_1);
    if (DEF_NOT_TASK_fgetc_0_EQ_SEL_ARR_0x50_0x35_1_pgm_re_ETC___d84)
      dollar_finish(sim_hdl, "32", 1u);
  }
}

void MOD_mkTb::RL_pgm_reader_fsm_action_f_update_l42c7()
{
  DEF_x__h52242 = INST_pgm_reader_i.METH_read();
  DEF_pgm_reader_i_2_PLUS_1___d87 = DEF_x__h52242 + 1u;
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)4u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  INST_pgm_reader_i.METH_write(DEF_pgm_reader_i_2_PLUS_1___d87);
}

void MOD_mkTb::RL_pgm_reader_fsm_action_f_init_l52c7()
{
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)5u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  INST_pgm_reader_i.METH_write(0u);
}

void MOD_mkTb::RL_pgm_reader_fsm_action_l52c28()
{
  tUInt32 DEF_SEL_ARR_pgm_reader_image_params_0_03_pgm_reade_ETC___d111;
  tUInt8 DEF_pgm_reader_i_2_EQ_0_6_AND_NOT_TASK_fgetc_7_SLT_ETC___d102;
  tUInt8 DEF_pgm_reader_i_2_EQ_1_12_AND_NOT_TASK_fgetc_7_SL_ETC___d113;
  tUInt8 DEF_NOT_TASK_fgetc_7_SLT_0x30_8_9_AND_TASK_fgetc_7_ETC___d101;
  tUInt8 DEF_pgm_reader_i_2_EQ_2_14_AND_NOT_TASK_fgetc_7_SL_ETC___d115;
  tUInt8 DEF_TASK_fgetc_7_SLT_0x30_8_OR_NOT_TASK_fgetc_7_SL_ETC___d136;
  tUInt8 DEF_TASK_fgetc_7_SLT_0x30_8_OR_NOT_TASK_fgetc_7_SL_ETC___d128;
  tUInt8 DEF_TASK_fgetc_7_EQ_0x9___d119;
  tUInt8 DEF_TASK_fgetc_7_EQ_0xA___d123;
  tUInt8 DEF_TASK_fgetc_7_EQ_0xD___d121;
  tUInt8 DEF_TASK_fgetc_7_EQ_0x20___d118;
  tUInt32 DEF_SEL_ARR_pgm_reader_image_params_0_03_pgm_reade_ETC___d107;
  tUInt32 DEF_b__h52118;
  tUInt8 DEF_TASK_fgetc_7_SLT_0x30_8_OR_NOT_TASK_fgetc_7_SL_ETC___d117;
  tUInt8 DEF_TASK_fgetc_7_SLT_0x30___d98;
  tUInt8 DEF_TASK_fgetc_7_SLE_0x39___d100;
  DEF_x__h78627 = INST_pgm_reader_image_params_1.METH_read();
  DEF_x__h78533 = INST_pgm_reader_image_params_0.METH_read();
  DEF_b__h52118 = INST_pgm_reader_image_params_2.METH_read();
  DEF_x__h52242 = INST_pgm_reader_i.METH_read();
  DEF_pgm_reader_filep__h50699 = INST_pgm_reader_filep.METH_read();
  switch (DEF_x__h52242) {
  case 0u:
    DEF_SEL_ARR_pgm_reader_image_params_0_03_pgm_reade_ETC___d107 = DEF_x__h78533;
    break;
  case 1u:
    DEF_SEL_ARR_pgm_reader_image_params_0_03_pgm_reade_ETC___d107 = DEF_x__h78627;
    break;
  case 2u:
    DEF_SEL_ARR_pgm_reader_image_params_0_03_pgm_reade_ETC___d107 = DEF_b__h52118;
    break;
  default:
    DEF_SEL_ARR_pgm_reader_image_params_0_03_pgm_reade_ETC___d107 = 2863311530u;
  }
  DEF_pgm_reader_i_2_PLUS_1___d87 = DEF_x__h52242 + 1u;
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)6u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_b__h51881 = dollar_fgetc("32", DEF_pgm_reader_filep__h50699);
  DEF_TASK_fgetc_7_SLE_0x39___d100 = primSLE8(1u, 32u, (tUInt32)(DEF_b__h51881), 32u, 57u);
  DEF_TASK_fgetc_7_SLT_0x30___d98 = primSLT8(1u, 32u, (tUInt32)(DEF_b__h51881), 32u, 48u);
  DEF_TASK_fgetc_7_SLT_0x30_8_OR_NOT_TASK_fgetc_7_SL_ETC___d117 = DEF_TASK_fgetc_7_SLT_0x30___d98 || !DEF_TASK_fgetc_7_SLE_0x39___d100;
  DEF_TASK_fgetc_7_EQ_0x20___d118 = DEF_b__h51881 == 32u;
  DEF_TASK_fgetc_7_EQ_0xD___d121 = DEF_b__h51881 == 13u;
  DEF_TASK_fgetc_7_EQ_0xA___d123 = DEF_b__h51881 == 10u;
  DEF_TASK_fgetc_7_EQ_0x9___d119 = DEF_b__h51881 == 9u;
  DEF_TASK_fgetc_7_SLT_0x30_8_OR_NOT_TASK_fgetc_7_SL_ETC___d128 = DEF_TASK_fgetc_7_SLT_0x30_8_OR_NOT_TASK_fgetc_7_SL_ETC___d117 && ((((DEF_TASK_fgetc_7_EQ_0x20___d118 || DEF_TASK_fgetc_7_EQ_0x9___d119) || DEF_TASK_fgetc_7_EQ_0xD___d121) || DEF_TASK_fgetc_7_EQ_0xA___d123) && !primSLE8(1u,
																																			     32u,
																																			     (tUInt32)(DEF_SEL_ARR_pgm_reader_image_params_0_03_pgm_reade_ETC___d107),
																																			     32u,
																																			     0u));
  DEF_TASK_fgetc_7_SLT_0x30_8_OR_NOT_TASK_fgetc_7_SL_ETC___d136 = DEF_TASK_fgetc_7_SLT_0x30_8_OR_NOT_TASK_fgetc_7_SL_ETC___d117 && (((!DEF_TASK_fgetc_7_EQ_0x20___d118 && !DEF_TASK_fgetc_7_EQ_0x9___d119) && !DEF_TASK_fgetc_7_EQ_0xD___d121) && !DEF_TASK_fgetc_7_EQ_0xA___d123);
  DEF_NOT_TASK_fgetc_7_SLT_0x30_8_9_AND_TASK_fgetc_7_ETC___d101 = !DEF_TASK_fgetc_7_SLT_0x30___d98 && DEF_TASK_fgetc_7_SLE_0x39___d100;
  DEF_pgm_reader_i_2_EQ_2_14_AND_NOT_TASK_fgetc_7_SL_ETC___d115 = DEF_x__h52242 == 2u && DEF_NOT_TASK_fgetc_7_SLT_0x30_8_9_AND_TASK_fgetc_7_ETC___d101;
  DEF_pgm_reader_i_2_EQ_1_12_AND_NOT_TASK_fgetc_7_SL_ETC___d113 = DEF_x__h52242 == 1u && DEF_NOT_TASK_fgetc_7_SLT_0x30_8_9_AND_TASK_fgetc_7_ETC___d101;
  DEF_pgm_reader_i_2_EQ_0_6_AND_NOT_TASK_fgetc_7_SLT_ETC___d102 = DEF_x__h52242 == 0u && DEF_NOT_TASK_fgetc_7_SLT_0x30_8_9_AND_TASK_fgetc_7_ETC___d101;
  DEF_SEL_ARR_pgm_reader_image_params_0_03_pgm_reade_ETC___d111 = (((tUInt32)(((tUInt64)(DEF_SEL_ARR_pgm_reader_image_params_0_03_pgm_reade_ETC___d107)) * ((tUInt64)(10u)))) + DEF_b__h51881) - 48u;
  if (DEF_pgm_reader_i_2_EQ_0_6_AND_NOT_TASK_fgetc_7_SLT_ETC___d102)
    INST_pgm_reader_image_params_0.METH_write(DEF_SEL_ARR_pgm_reader_image_params_0_03_pgm_reade_ETC___d111);
  if (DEF_pgm_reader_i_2_EQ_1_12_AND_NOT_TASK_fgetc_7_SL_ETC___d113)
    INST_pgm_reader_image_params_1.METH_write(DEF_SEL_ARR_pgm_reader_image_params_0_03_pgm_reade_ETC___d111);
  if (DEF_pgm_reader_i_2_EQ_2_14_AND_NOT_TASK_fgetc_7_SL_ETC___d115)
    INST_pgm_reader_image_params_2.METH_write(DEF_SEL_ARR_pgm_reader_image_params_0_03_pgm_reade_ETC___d111);
  if (DEF_TASK_fgetc_7_SLT_0x30_8_OR_NOT_TASK_fgetc_7_SL_ETC___d128)
    INST_pgm_reader_i.METH_write(DEF_pgm_reader_i_2_PLUS_1___d87);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_TASK_fgetc_7_SLT_0x30_8_OR_NOT_TASK_fgetc_7_SL_ETC___d136)
      dollar_error(sim_hdl, this, "s,s", &__str_literal_5, &__str_literal_1);
    if (DEF_TASK_fgetc_7_SLT_0x30_8_OR_NOT_TASK_fgetc_7_SL_ETC___d136)
      dollar_finish(sim_hdl, "32", 1u);
  }
}

void MOD_mkTb::RL_pgm_reader_fsm_action_f_update_l52c7()
{
  DEF_x__h52242 = INST_pgm_reader_i.METH_read();
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)7u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  INST_pgm_reader_i.METH_write(DEF_x__h52242);
}

void MOD_mkTb::RL_pgm_reader_fsm_action_f_init_l66c7()
{
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)8u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  INST_pgm_reader_i.METH_write(0u);
}

void MOD_mkTb::RL_pgm_reader_fsm_action_f_init_l67c10()
{
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)9u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  INST_pgm_reader_j.METH_write(0u);
}

void MOD_mkTb::RL_pgm_reader_fsm_action_l67c33()
{
  tUInt64 DEF_x__h54150;
  tUInt64 DEF_pgm_reader_load_pixels_BITS_63_TO_8___h54197;
  DEF_pgm_reader_load_pixels__h56216 = INST_pgm_reader_load_pixels.METH_read();
  DEF_pgm_reader_filep__h50699 = INST_pgm_reader_filep.METH_read();
  DEF_pgm_reader_load_pixels_BITS_63_TO_8___h54197 = (tUInt64)(DEF_pgm_reader_load_pixels__h56216 >> 8u);
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)10u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_TASK_fgetc___d156 = dollar_fgetc("32", DEF_pgm_reader_filep__h50699);
  DEF_x__h54150 = (((tUInt64)((tUInt8)((tUInt8)255u & DEF_TASK_fgetc___d156))) << 56u) | DEF_pgm_reader_load_pixels_BITS_63_TO_8___h54197;
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  INST_pgm_reader_load_pixels.METH_write(DEF_x__h54150);
}

void MOD_mkTb::RL_pgm_reader_fsm_action_f_update_l67c10()
{
  tUInt32 DEF_pgm_reader_j_49_PLUS_1___d163;
  DEF_b__h24176 = INST_pgm_reader_j.METH_read();
  DEF_pgm_reader_j_49_PLUS_1___d163 = DEF_b__h24176 + 1u;
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)11u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  INST_pgm_reader_j.METH_write(DEF_pgm_reader_j_49_PLUS_1___d163);
}

void MOD_mkTb::RL_pgm_reader_fsm_action_l71c20()
{
  DEF_pgm_reader_load_pixels__h56216 = INST_pgm_reader_load_pixels.METH_read();
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)12u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  INST_pgm_reader_pixel_fifo_wDataIn.METH_wset(DEF_pgm_reader_load_pixels__h56216);
  INST_pgm_reader_pixel_fifo_pwEnqueue.METH_wset();
}

void MOD_mkTb::RL_pgm_reader_fsm_action_f_update_l66c7()
{
  tUInt32 DEF_pgm_reader_i_2_PLUS_8___d172;
  DEF_x__h52242 = INST_pgm_reader_i.METH_read();
  DEF_pgm_reader_i_2_PLUS_8___d172 = DEF_x__h52242 + 8u;
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)13u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  INST_pgm_reader_i.METH_write(DEF_pgm_reader_i_2_PLUS_8___d172);
}

void MOD_mkTb::RL_pgm_reader_fsm_action_l74c7()
{
  DEF_pgm_reader_filep__h50699 = INST_pgm_reader_filep.METH_read();
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)14u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_fclose("32", DEF_pgm_reader_filep__h50699);
}

void MOD_mkTb::RL_pgm_reader_fsm_action_l75c7()
{
  tUInt32 DEF_signed_pgm_reader_image_params_0_03___d177;
  tUInt32 DEF_signed_pgm_reader_image_params_1_04___d178;
  DEF_x__h78627 = INST_pgm_reader_image_params_1.METH_read();
  DEF_signed_pgm_reader_image_params_1_04___d178 = DEF_x__h78627;
  DEF_x__h78533 = INST_pgm_reader_image_params_0.METH_read();
  DEF_signed_pgm_reader_image_params_0_03___d177 = DEF_x__h78533;
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)15u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,-32,-32",
		   &__str_literal_6,
		   DEF_signed_pgm_reader_image_params_0_03___d177,
		   DEF_signed_pgm_reader_image_params_1_04___d178);
}

void MOD_mkTb::RL_pgm_reader_fsm_idle_l30c23()
{
  INST_pgm_reader_fsm_state_mkFSMstate.METH_write((tUInt8)0u);
  INST_pgm_reader_fsm_state_fired_1.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_state_set_pw.METH_wset();
}

void MOD_mkTb::RL_pgm_reader_fsm_fsm_start()
{
  INST_pgm_reader_fsm_start_wire.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_start_reg_2.METH_wset((tUInt8)1u);
  INST_pgm_reader_fsm_start_reg.METH_write((tUInt8)0u);
}

void MOD_mkTb::RL_pgm_reader_start_fsm()
{
  INST_pgm_reader_fsm_start_reg.METH_write((tUInt8)1u);
}

void MOD_mkTb::RL_start_reg__dreg_update()
{
  tUInt8 DEF_start_reg_2_whas__90_AND_start_reg_2_wget__91___d192;
  DEF_start_reg_2_whas__90_AND_start_reg_2_wget__91___d192 = INST_start_reg_2.METH_whas() && INST_start_reg_2.METH_wget();
  INST_start_reg_1.METH_write(DEF_start_reg_2_whas__90_AND_start_reg_2_wget__91___d192);
}

void MOD_mkTb::RL_state_handle_abort()
{
  INST_state_mkFSMstate.METH_write((tUInt8)0u);
}

void MOD_mkTb::RL_state_fired__dreg_update()
{
  tUInt8 DEF_state_fired_1_whas__02_AND_state_fired_1_wget__03___d204;
  DEF_state_fired_1_whas__02_AND_state_fired_1_wget__03___d204 = INST_state_fired_1.METH_whas() && INST_state_fired_1.METH_wget();
  INST_state_fired.METH_write(DEF_state_fired_1_whas__02_AND_state_fired_1_wget__03___d204);
}

void MOD_mkTb::RL_state_every()
{
  tUInt8 DEF_state_set_pw_whas__05_OR_NOT_state_overlap_pw__ETC___d210;
  tUInt8 DEF_state_can_overlap__h61228;
  DEF_state_can_overlap__h61228 = INST_state_can_overlap.METH_read();
  DEF_state_set_pw_whas__05_OR_NOT_state_overlap_pw__ETC___d210 = INST_state_set_pw.METH_whas() || (!INST_state_overlap_pw.METH_whas() && DEF_state_can_overlap__h61228);
  INST_state_can_overlap.METH_write(DEF_state_set_pw_whas__05_OR_NOT_state_overlap_pw__ETC___d210);
}

void MOD_mkTb::RL_restart()
{
  INST_start_wire.METH_wset((tUInt8)1u);
  INST_start_reg_2.METH_wset((tUInt8)1u);
}

void MOD_mkTb::RL_action_l20c7()
{
  INST_state_mkFSMstate.METH_write((tUInt8)1u);
  INST_state_fired_1.METH_wset((tUInt8)1u);
  INST_state_set_pw.METH_wset();
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_TASK_fopen___d237 = dollar_fopen("s,s", &__str_literal_7, &__str_literal_8);
  INST_jpg_file.METH_write(DEF_TASK_fopen___d237);
}

void MOD_mkTb::RL_action_l25c7()
{
  tUInt8 DEF_NOT_IF_pgm_reader_image_params_0_03_BIT_31_46__ETC___d264;
  tUInt32 DEF__0_CONCAT_IF_pgm_reader_image_params_0_03_BIT_3_ETC___d250;
  tUInt32 DEF_IF_pgm_reader_image_params_0_03_BIT_31_46_THEN_ETC___d265;
  tUInt32 DEF__0_CONCAT_IF_pgm_reader_image_params_1_04_BIT_3_ETC___d259;
  tUInt32 DEF_IF_pgm_reader_image_params_1_04_BIT_31_55_THEN_ETC___d269;
  tUInt8 DEF_pgm_reader_image_params_0_03_BIT_31___d246;
  tUInt8 DEF_pgm_reader_image_params_1_04_BIT_31___d255;
  tUInt32 DEF_IF_pgm_reader_image_params_0_03_BIT_31_46_THEN_ETC___d248;
  tUInt32 DEF_IF_pgm_reader_image_params_1_04_BIT_31_55_THEN_ETC___d257;
  tUInt32 DEF_b__h78550;
  tUInt32 DEF_b__h78454;
  DEF_x__h78627 = INST_pgm_reader_image_params_1.METH_read();
  DEF_x__h78533 = INST_pgm_reader_image_params_0.METH_read();
  DEF_pgm_reader_image_params_1_04_BIT_31___d255 = (tUInt8)(DEF_x__h78627 >> 31u);
  DEF_IF_pgm_reader_image_params_1_04_BIT_31_55_THEN_ETC___d257 = DEF_pgm_reader_image_params_1_04_BIT_31___d255 ? -DEF_x__h78627 : DEF_x__h78627;
  DEF_pgm_reader_image_params_0_03_BIT_31___d246 = (tUInt8)(DEF_x__h78533 >> 31u);
  DEF_IF_pgm_reader_image_params_0_03_BIT_31_46_THEN_ETC___d248 = DEF_pgm_reader_image_params_0_03_BIT_31___d246 ? -DEF_x__h78533 : DEF_x__h78533;
  DEF_IF_pgm_reader_image_params_1_04_BIT_31_55_THEN_ETC___d269 = primShiftR32(32u,
									       32u,
									       (tUInt32)(DEF_IF_pgm_reader_image_params_1_04_BIT_31_55_THEN_ETC___d257),
									       32u,
									       3u);
  DEF_b__h78550 = (tUInt32)(511u & (DEF_pgm_reader_image_params_1_04_BIT_31___d255 ? -DEF_IF_pgm_reader_image_params_1_04_BIT_31_55_THEN_ETC___d269 : DEF_IF_pgm_reader_image_params_1_04_BIT_31_55_THEN_ETC___d269));
  DEF__0_CONCAT_IF_pgm_reader_image_params_1_04_BIT_3_ETC___d259 = (tUInt32)((tUInt8)((tUInt8)7u & DEF_IF_pgm_reader_image_params_1_04_BIT_31_55_THEN_ETC___d257));
  DEF_IF_pgm_reader_image_params_0_03_BIT_31_46_THEN_ETC___d265 = primShiftR32(32u,
									       32u,
									       (tUInt32)(DEF_IF_pgm_reader_image_params_0_03_BIT_31_46_THEN_ETC___d248),
									       32u,
									       3u);
  DEF_b__h78454 = (tUInt32)(511u & (DEF_pgm_reader_image_params_0_03_BIT_31___d246 ? -DEF_IF_pgm_reader_image_params_0_03_BIT_31_46_THEN_ETC___d265 : DEF_IF_pgm_reader_image_params_0_03_BIT_31_46_THEN_ETC___d265));
  DEF__0_CONCAT_IF_pgm_reader_image_params_0_03_BIT_3_ETC___d250 = (tUInt32)((tUInt8)((tUInt8)7u & DEF_IF_pgm_reader_image_params_0_03_BIT_31_46_THEN_ETC___d248));
  DEF_NOT_IF_pgm_reader_image_params_0_03_BIT_31_46__ETC___d264 = !((DEF_pgm_reader_image_params_0_03_BIT_31___d246 ? -DEF__0_CONCAT_IF_pgm_reader_image_params_0_03_BIT_3_ETC___d250 : DEF__0_CONCAT_IF_pgm_reader_image_params_0_03_BIT_3_ETC___d250) == 0u) || !((DEF_pgm_reader_image_params_1_04_BIT_31___d255 ? -DEF__0_CONCAT_IF_pgm_reader_image_params_1_04_BIT_3_ETC___d259 : DEF__0_CONCAT_IF_pgm_reader_image_params_1_04_BIT_3_ETC___d259) == 0u);
  INST_state_mkFSMstate.METH_write((tUInt8)2u);
  INST_state_fired_1.METH_wset((tUInt8)1u);
  INST_state_set_pw.METH_wset();
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_NOT_IF_pgm_reader_image_params_0_03_BIT_31_46__ETC___d264)
      dollar_error(sim_hdl, this, "s", &__str_literal_9);
    if (DEF_NOT_IF_pgm_reader_image_params_0_03_BIT_31_46__ETC___d264)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_jpg_encoder.METH_init(DEF_b__h78454, DEF_b__h78550);
}

void MOD_mkTb::RL_action_l36c10()
{
  tUInt64 DEF_pgm_reader_pixel_fifo_wDataOut_wget____d285;
  DEF_pgm_reader_pixel_fifo_wDataOut_wget____d285 = INST_pgm_reader_pixel_fifo_wDataOut.METH_wget();
  INST_state_mkFSMstate.METH_write((tUInt8)3u);
  INST_state_fired_1.METH_wset((tUInt8)1u);
  INST_state_set_pw.METH_wset();
  INST_jpg_encoder.METH_put(DEF_pgm_reader_pixel_fifo_wDataOut_wget____d285);
  INST_pgm_reader_pixel_fifo_pwDequeue.METH_wset();
}

void MOD_mkTb::RL_action_d_init_np()
{
  INST_state_mkFSMstate.METH_write((tUInt8)4u);
  INST_state_fired_1.METH_wset((tUInt8)1u);
  INST_state_set_pw.METH_wset();
  INST_jj_delay_count.METH_write(0u);
}

void MOD_mkTb::RL_action_np()
{
  tUInt32 DEF_x__h80660;
  DEF_jj_delay_count_read____d225 = INST_jj_delay_count.METH_read();
  DEF_x__h80660 = 16383u & (DEF_jj_delay_count_read____d225 + 1u);
  INST_state_mkFSMstate.METH_write((tUInt8)5u);
  INST_state_fired_1.METH_wset((tUInt8)1u);
  INST_state_set_pw.METH_wset();
  INST_jj_delay_count.METH_write(DEF_x__h80660);
}

void MOD_mkTb::RL_idle_l19c15()
{
  INST_state_mkFSMstate.METH_write((tUInt8)0u);
  INST_state_fired_1.METH_wset((tUInt8)1u);
  INST_state_set_pw.METH_wset();
}

void MOD_mkTb::RL_idle_l19c15_1()
{
  INST_state_mkFSMstate.METH_write((tUInt8)0u);
  INST_state_fired_1.METH_wset((tUInt8)1u);
  INST_state_set_pw.METH_wset();
}

void MOD_mkTb::RL_fsm_start()
{
  INST_start_wire.METH_wset((tUInt8)1u);
  INST_start_reg_2.METH_wset((tUInt8)1u);
  INST_start_reg.METH_write((tUInt8)0u);
}

void MOD_mkTb::RL_auto_start()
{
  INST_start_reg.METH_write((tUInt8)1u);
  INST_running.METH_write((tUInt8)1u);
}

void MOD_mkTb::RL_auto_finish()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_finish(sim_hdl, "32", 0u);
}

void MOD_mkTb::RL_write_jpg_to_file()
{
  tUInt32 DEF_jpg_file__h81165;
  DEF_x_get__h58249 = INST_jpg_encoder.METH_get();
  DEF_jpg_file__h81165 = INST_jpg_file.METH_read();
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_fwrite(sim_hdl,
		  this,
		  "32,s,128p",
		  DEF_jpg_file__h81165,
		  &__str_literal_10,
		  &DEF_x_get__h58249);
}

void MOD_mkTb::__me_check_8()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l32c7 && (((((((((((((DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l42c7 || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l42c30) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7))
      dollar_error(sim_hdl, this, "s", &__str_literal_11);
}

void MOD_mkTb::__me_check_9()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l42c7 && ((((((((((((DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l42c30 || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7))
      dollar_error(sim_hdl, this, "s", &__str_literal_12);
}

void MOD_mkTb::__me_check_10()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l42c30 && (((((((((((DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7 || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7))
      dollar_error(sim_hdl, this, "s", &__str_literal_13);
}

void MOD_mkTb::__me_check_11()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7 && ((((((((((DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7 || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7))
      dollar_error(sim_hdl, this, "s", &__str_literal_14);
}

void MOD_mkTb::__me_check_12()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7 && (((((((((DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28 || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7))
      dollar_error(sim_hdl, this, "s", &__str_literal_15);
}

void MOD_mkTb::__me_check_13()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28 && ((((((((DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7 || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7))
      dollar_error(sim_hdl, this, "s", &__str_literal_16);
}

void MOD_mkTb::__me_check_14()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7 && (((((((DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7 || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7))
      dollar_error(sim_hdl, this, "s", &__str_literal_17);
}

void MOD_mkTb::__me_check_15()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7 && ((((((DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10 || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7))
      dollar_error(sim_hdl, this, "s", &__str_literal_18);
}

void MOD_mkTb::__me_check_16()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10 && (((((DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33 || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7))
      dollar_error(sim_hdl, this, "s", &__str_literal_19);
}

void MOD_mkTb::__me_check_17()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33 && ((((DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10 || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7))
      dollar_error(sim_hdl, this, "s", &__str_literal_20);
}

void MOD_mkTb::__me_check_18()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10 && (((DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20 || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7))
      dollar_error(sim_hdl, this, "s", &__str_literal_21);
}

void MOD_mkTb::__me_check_19()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20 && ((DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7 || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7) || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7))
      dollar_error(sim_hdl, this, "s", &__str_literal_22);
}

void MOD_mkTb::__me_check_20()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7 && (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7 || DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7))
      dollar_error(sim_hdl, this, "s", &__str_literal_23);
}

void MOD_mkTb::__me_check_21()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7 && DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7)
      dollar_error(sim_hdl, this, "s", &__str_literal_24);
}

void MOD_mkTb::__me_check_31()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_action_l20c7 && (((DEF_WILL_FIRE_RL_action_l25c7 || DEF_WILL_FIRE_RL_action_l36c10) || DEF_WILL_FIRE_RL_action_d_init_np) || DEF_WILL_FIRE_RL_action_np))
      dollar_error(sim_hdl, this, "s", &__str_literal_25);
}

void MOD_mkTb::__me_check_32()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_action_l25c7 && ((DEF_WILL_FIRE_RL_action_l36c10 || DEF_WILL_FIRE_RL_action_d_init_np) || DEF_WILL_FIRE_RL_action_np))
      dollar_error(sim_hdl, this, "s", &__str_literal_26);
}

void MOD_mkTb::__me_check_33()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_action_l36c10 && (DEF_WILL_FIRE_RL_action_d_init_np || DEF_WILL_FIRE_RL_action_np))
      dollar_error(sim_hdl, this, "s", &__str_literal_27);
}

void MOD_mkTb::__me_check_34()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_WILL_FIRE_RL_action_d_init_np && DEF_WILL_FIRE_RL_action_np)
      dollar_error(sim_hdl, this, "s", &__str_literal_28);
}


/* Methods */


/* Reset routines */

void MOD_mkTb::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_state_mkFSMstate.reset_RST(ARG_rst_in);
  INST_state_fired.reset_RST(ARG_rst_in);
  INST_state_can_overlap.reset_RST(ARG_rst_in);
  INST_start_reg_1.reset_RST(ARG_rst_in);
  INST_start_reg.reset_RST(ARG_rst_in);
  INST_running.reset_RST(ARG_rst_in);
  INST_pgm_reader_pixel_fifo_rWrPtr.reset_RST(ARG_rst_in);
  INST_pgm_reader_pixel_fifo_rRdPtr.reset_RST(ARG_rst_in);
  INST_pgm_reader_pixel_fifo_rCache.reset_RST(ARG_rst_in);
  INST_pgm_reader_load_pixels.reset_RST(ARG_rst_in);
  INST_pgm_reader_j.reset_RST(ARG_rst_in);
  INST_pgm_reader_image_params_2.reset_RST(ARG_rst_in);
  INST_pgm_reader_image_params_1.reset_RST(ARG_rst_in);
  INST_pgm_reader_image_params_0.reset_RST(ARG_rst_in);
  INST_pgm_reader_i.reset_RST(ARG_rst_in);
  INST_pgm_reader_fsm_state_mkFSMstate.reset_RST(ARG_rst_in);
  INST_pgm_reader_fsm_state_fired.reset_RST(ARG_rst_in);
  INST_pgm_reader_fsm_state_can_overlap.reset_RST(ARG_rst_in);
  INST_pgm_reader_fsm_start_reg_1.reset_RST(ARG_rst_in);
  INST_pgm_reader_fsm_start_reg.reset_RST(ARG_rst_in);
  INST_pgm_reader_filep.reset_RST(ARG_rst_in);
  INST_jpg_file.reset_RST(ARG_rst_in);
  INST_jpg_encoder.reset_RST_N(ARG_rst_in);
  INST_jj_delay_count.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTb::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTb::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_abort.dump_state(indent + 2u);
  INST_jj_delay_count.dump_state(indent + 2u);
  INST_jpg_encoder.dump_state(indent + 2u);
  INST_jpg_file.dump_state(indent + 2u);
  INST_pgm_reader_filep.dump_state(indent + 2u);
  INST_pgm_reader_fsm_abort.dump_state(indent + 2u);
  INST_pgm_reader_fsm_start_reg.dump_state(indent + 2u);
  INST_pgm_reader_fsm_start_reg_1.dump_state(indent + 2u);
  INST_pgm_reader_fsm_start_reg_2.dump_state(indent + 2u);
  INST_pgm_reader_fsm_start_wire.dump_state(indent + 2u);
  INST_pgm_reader_fsm_state_can_overlap.dump_state(indent + 2u);
  INST_pgm_reader_fsm_state_fired.dump_state(indent + 2u);
  INST_pgm_reader_fsm_state_fired_1.dump_state(indent + 2u);
  INST_pgm_reader_fsm_state_mkFSMstate.dump_state(indent + 2u);
  INST_pgm_reader_fsm_state_overlap_pw.dump_state(indent + 2u);
  INST_pgm_reader_fsm_state_set_pw.dump_state(indent + 2u);
  INST_pgm_reader_i.dump_state(indent + 2u);
  INST_pgm_reader_image_params_0.dump_state(indent + 2u);
  INST_pgm_reader_image_params_1.dump_state(indent + 2u);
  INST_pgm_reader_image_params_2.dump_state(indent + 2u);
  INST_pgm_reader_j.dump_state(indent + 2u);
  INST_pgm_reader_load_pixels.dump_state(indent + 2u);
  INST_pgm_reader_pixel_fifo_memory.dump_state(indent + 2u);
  INST_pgm_reader_pixel_fifo_pwClear.dump_state(indent + 2u);
  INST_pgm_reader_pixel_fifo_pwDequeue.dump_state(indent + 2u);
  INST_pgm_reader_pixel_fifo_pwEnqueue.dump_state(indent + 2u);
  INST_pgm_reader_pixel_fifo_rCache.dump_state(indent + 2u);
  INST_pgm_reader_pixel_fifo_rRdPtr.dump_state(indent + 2u);
  INST_pgm_reader_pixel_fifo_rWrPtr.dump_state(indent + 2u);
  INST_pgm_reader_pixel_fifo_wDataIn.dump_state(indent + 2u);
  INST_pgm_reader_pixel_fifo_wDataOut.dump_state(indent + 2u);
  INST_running.dump_state(indent + 2u);
  INST_start_reg.dump_state(indent + 2u);
  INST_start_reg_1.dump_state(indent + 2u);
  INST_start_reg_2.dump_state(indent + 2u);
  INST_start_wire.dump_state(indent + 2u);
  INST_state_can_overlap.dump_state(indent + 2u);
  INST_state_fired.dump_state(indent + 2u);
  INST_state_fired_1.dump_state(indent + 2u);
  INST_state_mkFSMstate.dump_state(indent + 2u);
  INST_state_overlap_pw.dump_state(indent + 2u);
  INST_state_set_pw.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTb::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 82u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_pgm_reader_pixel_fifo_pwClear_whas___d7", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "TASK_fgetc___d156", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "TASK_fopen___d237", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "TASK_fopen___d67", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_action_d_init_np", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_action_l20c7", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_action_l25c7", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_action_l36c10", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_action_np", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l42c7", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_l32c7", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_l42c30", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_l52c28", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_l67c33", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_l71c20", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_l74c7", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_pgm_reader_fsm_action_l75c7", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_1_CONCAT_pgm_reader_pixel_fifo_rWrPtr_read_CON_ETC___d14", 88u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h24176", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h50673", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h51881", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "jj_delay_count_read____d225", 14u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "pgm_reader_filep__h50699", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "pgm_reader_i_2_PLUS_1___d87", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "pgm_reader_load_pixels__h56216", 64u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "pgm_reader_pixel_fifo_pwClear_whas____d1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "pgm_reader_pixel_fifo_rCache___d23", 88u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h3193", 23u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h52242", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h5481", 23u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h78533", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h78627", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_get__h58249", 128u);
  num = INST_abort.dump_VCD_defs(num);
  num = INST_jj_delay_count.dump_VCD_defs(num);
  num = INST_jpg_file.dump_VCD_defs(num);
  num = INST_pgm_reader_filep.dump_VCD_defs(num);
  num = INST_pgm_reader_fsm_abort.dump_VCD_defs(num);
  num = INST_pgm_reader_fsm_start_reg.dump_VCD_defs(num);
  num = INST_pgm_reader_fsm_start_reg_1.dump_VCD_defs(num);
  num = INST_pgm_reader_fsm_start_reg_2.dump_VCD_defs(num);
  num = INST_pgm_reader_fsm_start_wire.dump_VCD_defs(num);
  num = INST_pgm_reader_fsm_state_can_overlap.dump_VCD_defs(num);
  num = INST_pgm_reader_fsm_state_fired.dump_VCD_defs(num);
  num = INST_pgm_reader_fsm_state_fired_1.dump_VCD_defs(num);
  num = INST_pgm_reader_fsm_state_mkFSMstate.dump_VCD_defs(num);
  num = INST_pgm_reader_fsm_state_overlap_pw.dump_VCD_defs(num);
  num = INST_pgm_reader_fsm_state_set_pw.dump_VCD_defs(num);
  num = INST_pgm_reader_i.dump_VCD_defs(num);
  num = INST_pgm_reader_image_params_0.dump_VCD_defs(num);
  num = INST_pgm_reader_image_params_1.dump_VCD_defs(num);
  num = INST_pgm_reader_image_params_2.dump_VCD_defs(num);
  num = INST_pgm_reader_j.dump_VCD_defs(num);
  num = INST_pgm_reader_load_pixels.dump_VCD_defs(num);
  num = INST_pgm_reader_pixel_fifo_memory.dump_VCD_defs(num);
  num = INST_pgm_reader_pixel_fifo_pwClear.dump_VCD_defs(num);
  num = INST_pgm_reader_pixel_fifo_pwDequeue.dump_VCD_defs(num);
  num = INST_pgm_reader_pixel_fifo_pwEnqueue.dump_VCD_defs(num);
  num = INST_pgm_reader_pixel_fifo_rCache.dump_VCD_defs(num);
  num = INST_pgm_reader_pixel_fifo_rRdPtr.dump_VCD_defs(num);
  num = INST_pgm_reader_pixel_fifo_rWrPtr.dump_VCD_defs(num);
  num = INST_pgm_reader_pixel_fifo_wDataIn.dump_VCD_defs(num);
  num = INST_pgm_reader_pixel_fifo_wDataOut.dump_VCD_defs(num);
  num = INST_running.dump_VCD_defs(num);
  num = INST_start_reg.dump_VCD_defs(num);
  num = INST_start_reg_1.dump_VCD_defs(num);
  num = INST_start_reg_2.dump_VCD_defs(num);
  num = INST_start_wire.dump_VCD_defs(num);
  num = INST_state_can_overlap.dump_VCD_defs(num);
  num = INST_state_fired.dump_VCD_defs(num);
  num = INST_state_fired_1.dump_VCD_defs(num);
  num = INST_state_mkFSMstate.dump_VCD_defs(num);
  num = INST_state_overlap_pw.dump_VCD_defs(num);
  num = INST_state_set_pw.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST_jpg_encoder.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTb::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTb &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mkTb::vcd_defs(tVCDDumpType dt, MOD_mkTb &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 88u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 14u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 64u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 88u);
    vcd_write_x(sim_hdl, num++, 23u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 23u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 128u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas___d7) != DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas___d7)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas___d7, 1u);
	backing.DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas___d7 = DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas___d7;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_TASK_fgetc___d156) != DEF_TASK_fgetc___d156)
      {
	vcd_write_val(sim_hdl, num, DEF_TASK_fgetc___d156, 32u);
	backing.DEF_TASK_fgetc___d156 = DEF_TASK_fgetc___d156;
      }
      ++num;
      if ((backing.DEF_TASK_fopen___d237) != DEF_TASK_fopen___d237)
      {
	vcd_write_val(sim_hdl, num, DEF_TASK_fopen___d237, 32u);
	backing.DEF_TASK_fopen___d237 = DEF_TASK_fopen___d237;
      }
      ++num;
      if ((backing.DEF_TASK_fopen___d67) != DEF_TASK_fopen___d67)
      {
	vcd_write_val(sim_hdl, num, DEF_TASK_fopen___d67, 32u);
	backing.DEF_TASK_fopen___d67 = DEF_TASK_fopen___d67;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_action_d_init_np) != DEF_WILL_FIRE_RL_action_d_init_np)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_action_d_init_np, 1u);
	backing.DEF_WILL_FIRE_RL_action_d_init_np = DEF_WILL_FIRE_RL_action_d_init_np;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_action_l20c7) != DEF_WILL_FIRE_RL_action_l20c7)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_action_l20c7, 1u);
	backing.DEF_WILL_FIRE_RL_action_l20c7 = DEF_WILL_FIRE_RL_action_l20c7;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_action_l25c7) != DEF_WILL_FIRE_RL_action_l25c7)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_action_l25c7, 1u);
	backing.DEF_WILL_FIRE_RL_action_l25c7 = DEF_WILL_FIRE_RL_action_l25c7;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_action_l36c10) != DEF_WILL_FIRE_RL_action_l36c10)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_action_l36c10, 1u);
	backing.DEF_WILL_FIRE_RL_action_l36c10 = DEF_WILL_FIRE_RL_action_l36c10;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_action_np) != DEF_WILL_FIRE_RL_action_np)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_action_np, 1u);
	backing.DEF_WILL_FIRE_RL_action_np = DEF_WILL_FIRE_RL_action_np;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l42c7) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l42c7)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l42c7, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l42c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l42c7;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l32c7) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l32c7)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l32c7, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l32c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l32c7;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l42c30) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l42c30)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l42c30, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l42c30 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l42c30;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7) != DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7, 1u);
	backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7;
      }
      ++num;
      if ((backing.DEF__1_CONCAT_pgm_reader_pixel_fifo_rWrPtr_read_CON_ETC___d14) != DEF__1_CONCAT_pgm_reader_pixel_fifo_rWrPtr_read_CON_ETC___d14)
      {
	vcd_write_val(sim_hdl, num, DEF__1_CONCAT_pgm_reader_pixel_fifo_rWrPtr_read_CON_ETC___d14, 88u);
	backing.DEF__1_CONCAT_pgm_reader_pixel_fifo_rWrPtr_read_CON_ETC___d14 = DEF__1_CONCAT_pgm_reader_pixel_fifo_rWrPtr_read_CON_ETC___d14;
      }
      ++num;
      if ((backing.DEF_b__h24176) != DEF_b__h24176)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h24176, 32u);
	backing.DEF_b__h24176 = DEF_b__h24176;
      }
      ++num;
      if ((backing.DEF_b__h50673) != DEF_b__h50673)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h50673, 32u);
	backing.DEF_b__h50673 = DEF_b__h50673;
      }
      ++num;
      if ((backing.DEF_b__h51881) != DEF_b__h51881)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h51881, 32u);
	backing.DEF_b__h51881 = DEF_b__h51881;
      }
      ++num;
      if ((backing.DEF_jj_delay_count_read____d225) != DEF_jj_delay_count_read____d225)
      {
	vcd_write_val(sim_hdl, num, DEF_jj_delay_count_read____d225, 14u);
	backing.DEF_jj_delay_count_read____d225 = DEF_jj_delay_count_read____d225;
      }
      ++num;
      if ((backing.DEF_pgm_reader_filep__h50699) != DEF_pgm_reader_filep__h50699)
      {
	vcd_write_val(sim_hdl, num, DEF_pgm_reader_filep__h50699, 32u);
	backing.DEF_pgm_reader_filep__h50699 = DEF_pgm_reader_filep__h50699;
      }
      ++num;
      if ((backing.DEF_pgm_reader_i_2_PLUS_1___d87) != DEF_pgm_reader_i_2_PLUS_1___d87)
      {
	vcd_write_val(sim_hdl, num, DEF_pgm_reader_i_2_PLUS_1___d87, 32u);
	backing.DEF_pgm_reader_i_2_PLUS_1___d87 = DEF_pgm_reader_i_2_PLUS_1___d87;
      }
      ++num;
      if ((backing.DEF_pgm_reader_load_pixels__h56216) != DEF_pgm_reader_load_pixels__h56216)
      {
	vcd_write_val(sim_hdl, num, DEF_pgm_reader_load_pixels__h56216, 64u);
	backing.DEF_pgm_reader_load_pixels__h56216 = DEF_pgm_reader_load_pixels__h56216;
      }
      ++num;
      if ((backing.DEF_pgm_reader_pixel_fifo_pwClear_whas____d1) != DEF_pgm_reader_pixel_fifo_pwClear_whas____d1)
      {
	vcd_write_val(sim_hdl, num, DEF_pgm_reader_pixel_fifo_pwClear_whas____d1, 1u);
	backing.DEF_pgm_reader_pixel_fifo_pwClear_whas____d1 = DEF_pgm_reader_pixel_fifo_pwClear_whas____d1;
      }
      ++num;
      if ((backing.DEF_pgm_reader_pixel_fifo_rCache___d23) != DEF_pgm_reader_pixel_fifo_rCache___d23)
      {
	vcd_write_val(sim_hdl, num, DEF_pgm_reader_pixel_fifo_rCache___d23, 88u);
	backing.DEF_pgm_reader_pixel_fifo_rCache___d23 = DEF_pgm_reader_pixel_fifo_rCache___d23;
      }
      ++num;
      if ((backing.DEF_x__h3193) != DEF_x__h3193)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h3193, 23u);
	backing.DEF_x__h3193 = DEF_x__h3193;
      }
      ++num;
      if ((backing.DEF_x__h52242) != DEF_x__h52242)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h52242, 32u);
	backing.DEF_x__h52242 = DEF_x__h52242;
      }
      ++num;
      if ((backing.DEF_x__h5481) != DEF_x__h5481)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h5481, 23u);
	backing.DEF_x__h5481 = DEF_x__h5481;
      }
      ++num;
      if ((backing.DEF_x__h78533) != DEF_x__h78533)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h78533, 32u);
	backing.DEF_x__h78533 = DEF_x__h78533;
      }
      ++num;
      if ((backing.DEF_x__h78627) != DEF_x__h78627)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h78627, 32u);
	backing.DEF_x__h78627 = DEF_x__h78627;
      }
      ++num;
      if ((backing.DEF_x_get__h58249) != DEF_x_get__h58249)
      {
	vcd_write_val(sim_hdl, num, DEF_x_get__h58249, 128u);
	backing.DEF_x_get__h58249 = DEF_x_get__h58249;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas___d7, 1u);
      backing.DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas___d7 = DEF_NOT_pgm_reader_pixel_fifo_pwClear_whas___d7;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_TASK_fgetc___d156, 32u);
      backing.DEF_TASK_fgetc___d156 = DEF_TASK_fgetc___d156;
      vcd_write_val(sim_hdl, num++, DEF_TASK_fopen___d237, 32u);
      backing.DEF_TASK_fopen___d237 = DEF_TASK_fopen___d237;
      vcd_write_val(sim_hdl, num++, DEF_TASK_fopen___d67, 32u);
      backing.DEF_TASK_fopen___d67 = DEF_TASK_fopen___d67;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_action_d_init_np, 1u);
      backing.DEF_WILL_FIRE_RL_action_d_init_np = DEF_WILL_FIRE_RL_action_d_init_np;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_action_l20c7, 1u);
      backing.DEF_WILL_FIRE_RL_action_l20c7 = DEF_WILL_FIRE_RL_action_l20c7;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_action_l25c7, 1u);
      backing.DEF_WILL_FIRE_RL_action_l25c7 = DEF_WILL_FIRE_RL_action_l25c7;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_action_l36c10, 1u);
      backing.DEF_WILL_FIRE_RL_action_l36c10 = DEF_WILL_FIRE_RL_action_l36c10;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_action_np, 1u);
      backing.DEF_WILL_FIRE_RL_action_np = DEF_WILL_FIRE_RL_action_np;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l42c7, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l42c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l42c7;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l52c7;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l66c7;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_init_l67c10;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l42c7;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l52c7;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l66c7;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_f_update_l67c10;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l32c7, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l32c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l32c7;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l42c30, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l42c30 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l42c30;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l52c28;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l67c33;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l71c20;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l74c7;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7, 1u);
      backing.DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7 = DEF_WILL_FIRE_RL_pgm_reader_fsm_action_l75c7;
      vcd_write_val(sim_hdl, num++, DEF__1_CONCAT_pgm_reader_pixel_fifo_rWrPtr_read_CON_ETC___d14, 88u);
      backing.DEF__1_CONCAT_pgm_reader_pixel_fifo_rWrPtr_read_CON_ETC___d14 = DEF__1_CONCAT_pgm_reader_pixel_fifo_rWrPtr_read_CON_ETC___d14;
      vcd_write_val(sim_hdl, num++, DEF_b__h24176, 32u);
      backing.DEF_b__h24176 = DEF_b__h24176;
      vcd_write_val(sim_hdl, num++, DEF_b__h50673, 32u);
      backing.DEF_b__h50673 = DEF_b__h50673;
      vcd_write_val(sim_hdl, num++, DEF_b__h51881, 32u);
      backing.DEF_b__h51881 = DEF_b__h51881;
      vcd_write_val(sim_hdl, num++, DEF_jj_delay_count_read____d225, 14u);
      backing.DEF_jj_delay_count_read____d225 = DEF_jj_delay_count_read____d225;
      vcd_write_val(sim_hdl, num++, DEF_pgm_reader_filep__h50699, 32u);
      backing.DEF_pgm_reader_filep__h50699 = DEF_pgm_reader_filep__h50699;
      vcd_write_val(sim_hdl, num++, DEF_pgm_reader_i_2_PLUS_1___d87, 32u);
      backing.DEF_pgm_reader_i_2_PLUS_1___d87 = DEF_pgm_reader_i_2_PLUS_1___d87;
      vcd_write_val(sim_hdl, num++, DEF_pgm_reader_load_pixels__h56216, 64u);
      backing.DEF_pgm_reader_load_pixels__h56216 = DEF_pgm_reader_load_pixels__h56216;
      vcd_write_val(sim_hdl, num++, DEF_pgm_reader_pixel_fifo_pwClear_whas____d1, 1u);
      backing.DEF_pgm_reader_pixel_fifo_pwClear_whas____d1 = DEF_pgm_reader_pixel_fifo_pwClear_whas____d1;
      vcd_write_val(sim_hdl, num++, DEF_pgm_reader_pixel_fifo_rCache___d23, 88u);
      backing.DEF_pgm_reader_pixel_fifo_rCache___d23 = DEF_pgm_reader_pixel_fifo_rCache___d23;
      vcd_write_val(sim_hdl, num++, DEF_x__h3193, 23u);
      backing.DEF_x__h3193 = DEF_x__h3193;
      vcd_write_val(sim_hdl, num++, DEF_x__h52242, 32u);
      backing.DEF_x__h52242 = DEF_x__h52242;
      vcd_write_val(sim_hdl, num++, DEF_x__h5481, 23u);
      backing.DEF_x__h5481 = DEF_x__h5481;
      vcd_write_val(sim_hdl, num++, DEF_x__h78533, 32u);
      backing.DEF_x__h78533 = DEF_x__h78533;
      vcd_write_val(sim_hdl, num++, DEF_x__h78627, 32u);
      backing.DEF_x__h78627 = DEF_x__h78627;
      vcd_write_val(sim_hdl, num++, DEF_x_get__h58249, 128u);
      backing.DEF_x_get__h58249 = DEF_x_get__h58249;
    }
}

void MOD_mkTb::vcd_prims(tVCDDumpType dt, MOD_mkTb &backing)
{
  INST_abort.dump_VCD(dt, backing.INST_abort);
  INST_jj_delay_count.dump_VCD(dt, backing.INST_jj_delay_count);
  INST_jpg_file.dump_VCD(dt, backing.INST_jpg_file);
  INST_pgm_reader_filep.dump_VCD(dt, backing.INST_pgm_reader_filep);
  INST_pgm_reader_fsm_abort.dump_VCD(dt, backing.INST_pgm_reader_fsm_abort);
  INST_pgm_reader_fsm_start_reg.dump_VCD(dt, backing.INST_pgm_reader_fsm_start_reg);
  INST_pgm_reader_fsm_start_reg_1.dump_VCD(dt, backing.INST_pgm_reader_fsm_start_reg_1);
  INST_pgm_reader_fsm_start_reg_2.dump_VCD(dt, backing.INST_pgm_reader_fsm_start_reg_2);
  INST_pgm_reader_fsm_start_wire.dump_VCD(dt, backing.INST_pgm_reader_fsm_start_wire);
  INST_pgm_reader_fsm_state_can_overlap.dump_VCD(dt, backing.INST_pgm_reader_fsm_state_can_overlap);
  INST_pgm_reader_fsm_state_fired.dump_VCD(dt, backing.INST_pgm_reader_fsm_state_fired);
  INST_pgm_reader_fsm_state_fired_1.dump_VCD(dt, backing.INST_pgm_reader_fsm_state_fired_1);
  INST_pgm_reader_fsm_state_mkFSMstate.dump_VCD(dt, backing.INST_pgm_reader_fsm_state_mkFSMstate);
  INST_pgm_reader_fsm_state_overlap_pw.dump_VCD(dt, backing.INST_pgm_reader_fsm_state_overlap_pw);
  INST_pgm_reader_fsm_state_set_pw.dump_VCD(dt, backing.INST_pgm_reader_fsm_state_set_pw);
  INST_pgm_reader_i.dump_VCD(dt, backing.INST_pgm_reader_i);
  INST_pgm_reader_image_params_0.dump_VCD(dt, backing.INST_pgm_reader_image_params_0);
  INST_pgm_reader_image_params_1.dump_VCD(dt, backing.INST_pgm_reader_image_params_1);
  INST_pgm_reader_image_params_2.dump_VCD(dt, backing.INST_pgm_reader_image_params_2);
  INST_pgm_reader_j.dump_VCD(dt, backing.INST_pgm_reader_j);
  INST_pgm_reader_load_pixels.dump_VCD(dt, backing.INST_pgm_reader_load_pixels);
  INST_pgm_reader_pixel_fifo_memory.dump_VCD(dt, backing.INST_pgm_reader_pixel_fifo_memory);
  INST_pgm_reader_pixel_fifo_pwClear.dump_VCD(dt, backing.INST_pgm_reader_pixel_fifo_pwClear);
  INST_pgm_reader_pixel_fifo_pwDequeue.dump_VCD(dt, backing.INST_pgm_reader_pixel_fifo_pwDequeue);
  INST_pgm_reader_pixel_fifo_pwEnqueue.dump_VCD(dt, backing.INST_pgm_reader_pixel_fifo_pwEnqueue);
  INST_pgm_reader_pixel_fifo_rCache.dump_VCD(dt, backing.INST_pgm_reader_pixel_fifo_rCache);
  INST_pgm_reader_pixel_fifo_rRdPtr.dump_VCD(dt, backing.INST_pgm_reader_pixel_fifo_rRdPtr);
  INST_pgm_reader_pixel_fifo_rWrPtr.dump_VCD(dt, backing.INST_pgm_reader_pixel_fifo_rWrPtr);
  INST_pgm_reader_pixel_fifo_wDataIn.dump_VCD(dt, backing.INST_pgm_reader_pixel_fifo_wDataIn);
  INST_pgm_reader_pixel_fifo_wDataOut.dump_VCD(dt, backing.INST_pgm_reader_pixel_fifo_wDataOut);
  INST_running.dump_VCD(dt, backing.INST_running);
  INST_start_reg.dump_VCD(dt, backing.INST_start_reg);
  INST_start_reg_1.dump_VCD(dt, backing.INST_start_reg_1);
  INST_start_reg_2.dump_VCD(dt, backing.INST_start_reg_2);
  INST_start_wire.dump_VCD(dt, backing.INST_start_wire);
  INST_state_can_overlap.dump_VCD(dt, backing.INST_state_can_overlap);
  INST_state_fired.dump_VCD(dt, backing.INST_state_fired);
  INST_state_fired_1.dump_VCD(dt, backing.INST_state_fired_1);
  INST_state_mkFSMstate.dump_VCD(dt, backing.INST_state_mkFSMstate);
  INST_state_overlap_pw.dump_VCD(dt, backing.INST_state_overlap_pw);
  INST_state_set_pw.dump_VCD(dt, backing.INST_state_set_pw);
}

void MOD_mkTb::vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTb &backing)
{
  INST_jpg_encoder.dump_VCD(dt, levels, backing.INST_jpg_encoder);
}
