/*
 * Generated by Bluespec Compiler, version 2022.01 (build 066c7a8)
 * 
 * On Fri Dec 23 17:43:33 CST 2022
 * 
 */
#include "bluesim_systemc.h"
#include "mkTb_systemc.h"

void mkTb::handle_CLK()
{
  static tClock _clk_hdl = bk_get_clock_by_name(_sim_hdl, "CLK");
  
  /* sample method input ports */
  
  /* update VCD waveforms for ports */
  tTime now = sc_time_stamp().value();
  bk_VCD_combo_update(_sim_hdl, now);
  
  /* execute schedule */
  tEdgeDirection dir = (CLK->read)() ? POSEDGE : NEGEDGE;
  bk_quit_after_edge(_sim_hdl, _clk_hdl, dir, bk_clock_edge_count(_sim_hdl, _clk_hdl, dir) + 1llu);
  bk_trigger_clock_edge(_sim_hdl, _clk_hdl, dir, now);
  bk_advance(_sim_hdl, false);
  if (bk_stopped(_sim_hdl) || (bk_finished(_sim_hdl) || bk_aborted(_sim_hdl)))
    sc_stop();
  
  /* update method output ports */
}

void mkTb::handle_RST_N()
{
  (_model_inst->reset_RST_N)((RST_N->read)());
}
