//
// Generated by Bluespec Compiler, version 2022.01 (build 066c7a8)
//
// On Sun May 14 20:36:21 CST 2023
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTb(CLK,
	    RST_N);
  input  CLK;
  input  RST_N;

  // ports of submodule counter
  wire [31 : 0] counter$count;
  wire counter$overflow;

  // submodule counter
  mkDecCounter counter(.CLK(CLK),
		       .RST_N(RST_N),
		       .count(counter$count),
		       .RDY_count(),
		       .overflow(counter$overflow),
		       .RDY_overflow());

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      $display("count=%d, oflow=%d",
	       $unsigned(counter$count),
	       counter$overflow);
    if (RST_N != `BSV_RESET_VALUE)
      if (counter$count > 32'd100000) $finish(32'd1);
  end
  // synopsys translate_on
endmodule  // mkTb

